#!/usr/bin/env python3
"""Combines what benchmark_key_commits.sh measured into one table.

https://github.com/asc-community/AngouriMath/issues/529

Two tables, because the two numbers are not the same kind of thing. Allocation is deterministic:
the same commit measured twice gives the same bytes, so a difference between two columns is a
difference in the code. The wall clock on a shared runner is not: the Kernel Benchmark run twice
on one unchanged commit has come back 30-57% apart on this project's own history, while its
allocation over the same pair agreed to 0.03%. So the times are printed and the allocations are
printed, and only the second is worth reading as a change on its own.

A commit that did not build is a row saying so. It is not omitted, because "this can no longer be
measured" is a finding — the benchmark is taken from master and calls the public API as it now is,
so an old enough commit stops being reachable this way, and the row is where that shows.
"""

import json
import os
import sys


def read_list(path):
    with open(path) as handle:
        return [line.strip() for line in handle
                if line.strip() and not line.strip().startswith("#")]


def read_results(directory, commit):
    status_path = os.path.join(directory, commit + ".status")
    status = "not attempted"
    if os.path.exists(status_path):
        with open(status_path) as handle:
            status = handle.read().strip()
    measured_path = os.path.join(directory, commit + ".json")
    measured = None
    if os.path.exists(measured_path):
        with open(measured_path) as handle:
            measured = json.load(handle)
        measured = cases_of(measured)
    return status, measured


def cases_of(document):
    """The {benchmark: {meanNanoseconds, allocatedBytes}} map inside a measured-*.json.

    Found by shape rather than only by name. The file also carries `comment`, `benchmark`,
    `commit`, `machine` and more at the top level, and reading it as though every key were a
    benchmark is what the first version of this did — it took `comment`, a string, and asked it
    for a field. Named `cases` today; a rename would break a lookup by name alone and would not
    break this.
    """
    if not isinstance(document, dict):
        return None
    for key in ("cases", "measurements", "results", "benchmarks"):
        if isinstance(document.get(key), dict):
            return document[key]
    for value in document.values():
        if (isinstance(value, dict) and value
                and all(isinstance(case, dict) and "meanNanoseconds" in case
                        for case in value.values())):
            return value
    return None


def column(measured, benchmark, field):
    if not measured or benchmark not in measured:
        return None
    value = measured[benchmark].get(field)
    return None if value is None else float(value)


def table(handle, commits, results, benchmarks, field, unit, heading, note):
    handle.write("\n### %s\n\n%s\n\n" % (heading, note))
    handle.write("| benchmark | " + " | ".join(commits) + " |\n")
    handle.write("|---" * (len(commits) + 1) + "|\n")
    for benchmark in benchmarks:
        cells = []
        for commit in commits:
            value = column(results[commit][1], benchmark, field)
            cells.append("—" if value is None else "{:,.0f}".format(value))
        handle.write("| `%s` | %s |\n" % (benchmark, " | ".join(cells)))
    handle.write("\nIn %s. A dash is a commit this benchmark has no figure for.\n" % unit)


def main():
    if len(sys.argv) != 4:
        print("usage: combine_key_commits.py <key-commits.txt> <results dir> <output>",
              file=sys.stderr)
        return 1
    list_path, results_directory, output = sys.argv[1:4]

    commits = read_list(list_path)
    results = {commit: read_results(results_directory, commit) for commit in commits}

    benchmarks = []
    for commit in commits:
        measured = results[commit][1]
        if measured:
            for name in measured:
                if name not in benchmarks:
                    benchmarks.append(name)
    benchmarks.sort()

    with open(output, "w") as handle:
        handle.write("# The kernel across key commits\n\n")
        handle.write("Generated by `Sources/Utils/benchmark_key_commits.sh`. "
                     "The benchmark is the one at master in every column; only the kernel "
                     "differs, which is what makes the columns comparable.\n\n")

        handle.write("| commit | outcome |\n|---|---|\n")
        for commit in commits:
            handle.write("| `%s` | %s |\n" % (commit, results[commit][0]))

        if not benchmarks:
            handle.write("\nNothing was measured, so there is no table to draw.\n")
            return 0

        table(handle, commits, results, benchmarks, "allocatedBytes", "bytes allocated",
              "Allocation",
              "**This is the one to read.** Allocation is deterministic — the same commit "
              "measured twice gives the same bytes — so a difference between two columns is a "
              "difference in the code rather than in the machine.")
        table(handle, commits, results, benchmarks, "meanNanoseconds", "nanoseconds",
              "Time",
              "Reported rather than relied on. On a shared runner this project has seen the "
              "same unchanged commit come back 30-57% apart, while its allocation over the same "
              "pair agreed to 0.03%. Read a movement here as a question, and answer it by "
              "re-running both columns on one machine.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
