//
// Copyright (c) 2019-2022 Angouri.
// AngouriMath is licensed under MIT.
// Details: https://github.com/asc-community/AngouriMath/blob/master/LICENSE.md.
// Website: https://am.angouri.org.
//

/*

The parser source files under the Antlr folder other than "Angourimath.g" are generated by ANTLR.
You should only modify "Angourimath.g", other source files are generated from this file.
Any modifications to other source files will be overwritten when the parser is regenerated.

*/

using Antlr4.Runtime;
using System;
using System.IO;
using System.Text;

[assembly: System.CLSCompliant(false)]
namespace AngouriMath.Core
{
    using Antlr;
    using Exceptions;
    using static ReasonOfFailureWhileParsing;

    /// <summary>
    /// Nesting class for reasons of why parsing could fail. The type union for it
    /// is 
    /// </summary>
    public abstract record ReasonOfFailureWhileParsing
    {
        /// <summary>
        /// The error is an unclassified error returned by the
        /// ANTLR's parser.
        /// </summary>
        public sealed record Unknown(string Reason);


        /// <summary>
        /// This error is when the explicit parsing mode is enabled,
        /// but the input lacks an operator (which is normally inserted
        /// automatically with explicit parsing mode turned off). For
        /// example, "2x" would give this error.
        /// </summary>
        public sealed record MissingOperator(string Details);

        /// <summary>
        /// This is a bug of AngouriMath. Something that we definitely
        /// do not expect. More: <see cref="AngouriMath.Core.Exceptions.AngouriBugException"/>.
        /// Please, report to the main repository.
        /// </summary>
        public sealed record InternalError(string Details);
    }
    
    

    internal static class Parser
    {
        // Antlr parser spams errors into TextWriter provided, we inherit from it to handle lexer/parser errors as ParseExceptions
        private sealed class AngouriMathTextWriter : TextWriter
        {
            public override Encoding Encoding => Encoding.UTF8;
            public override void WriteLine(string? s) => errors.Add(new Unknown(s ?? throw new System.ArgumentNullException()));
            public readonly List<ReasonWhyParsingFailed> errors = new();
        }
        
        private static int? GetNextToken(IList<IToken> tokens, int currPos)
        {
            while (tokens[currPos].Channel != 0)
                if (++currPos >= tokens.Count)
                    return null;
            return currPos;
        }
        
        /// <summary>
        /// This method inserts omitted tokens when no
        /// explicit-only parsing is enabled. Otherwise,
        /// it will throw an exception.
        /// </summary>
        private static Either<Unit, ReasonWhyParsingFailed> InsertOmittedTokensOrProvideDiagnostic(IList<IToken> tokenList, AngouriMathLexer lexer)
        {
            const string NUMBER = nameof(NUMBER);
            const string VARIABLE = nameof(VARIABLE);
            const string PARENTHESIS_OPEN = "'('";
            const string PARENTHESIS_CLOSE = "')'";
            const string FUNCTION_OPEN = "\x1"; // Fake display name for all function tokens e.g. "'sin('"
         
            if (GetNextToken(tokenList, 0) is not { } leftId)
                return new Unit();
            
            for (var rightId = leftId + 1; rightId < tokenList.Count; leftId = rightId++)
            {
                if (GetNextToken(tokenList, rightId) is not { } nextRightId)
                    return new Unit();
                rightId = nextRightId;
                if ((GetType(tokenList[leftId]), GetType(tokenList[rightId])) switch
                    {
                        // 2x -> 2 * x       2sqrt -> 2 * sqrt       2( -> 2 * (
                        // x y -> x * y      x sqrt -> x * sqrt      x( -> x * (
                        // )x -> ) * x       )sqrt -> ) * sqrt       )( -> ) * (
                        (NUMBER or VARIABLE or PARENTHESIS_CLOSE, VARIABLE or FUNCTION_OPEN or PARENTHESIS_OPEN)
                            => lexer.Multiply,
                        // 3 2 -> 3 ^ 2      x2 -> x ^ 2             )2 -> ) ^ 2
                        (NUMBER or VARIABLE or PARENTHESIS_CLOSE, NUMBER) => lexer.Power,

                        _ => null
                    } is { } insertToken)
                    {
                        if (!MathS.Settings.ExplicitParsingOnly)
                            // Insert at j because we need to keep the first one behind
                            tokenList.Insert(rightId, insertToken);
                        else
                            return new ReasonWhyParsingFailed(new MissingOperator($"There should be an operator between {tokenList[leftId]} and {tokenList[rightId]}"));
                    }
            }
            
            return new Unit();
            
            static string GetType(IToken token) =>
                AngouriMathLexer.DefaultVocabulary.GetDisplayName(token.Type) is var type
                && type is not PARENTHESIS_OPEN && type.EndsWith("('") ? FUNCTION_OPEN : type;
        }
        
        internal static Either<Entity, Failure<ReasonWhyParsingFailed>> ParseSilent(string source)
        {
            var writer = new AngouriMathTextWriter();

            if (writer.errors.Count > 0)
                return new Failure<ReasonWhyParsingFailed>(writer.errors[0]);

            var lexer = new AngouriMathLexer(new AntlrInputStream(source), null, writer);
            var tokenStream = new CommonTokenStream(lexer);
            tokenStream.Fill();
            var tokenList = tokenStream.GetTokens();            

            if (tokenList.Count is 0)
                return new Failure<ReasonWhyParsingFailed>(
                    new ReasonWhyParsingFailed(
                        new InternalError(
                            $"{nameof(ParseException)} should have been thrown"
                        )
                    )
                );
            
            if (InsertOmittedTokensOrProvideDiagnostic(tokenList, lexer).Is<ReasonWhyParsingFailed>(out var whyFailed))
                return new Failure<ReasonWhyParsingFailed>(whyFailed);

            
            var parser = new AngouriMathParser(tokenStream, null, writer);

            // ANTLR reports a syntax error to the listener and then *recovers*, carrying on
            // with a rule context whose value was never assigned. The grammar's actions run
            // anyway and dereference it, so an invalid input can bring the parse down before
            // the error already sitting in `writer.errors` is ever read. Reading it is the
            // honest answer: the input really was invalid, and that is what the caller is
            // owed -- an exception under AngouriMathBaseException, as Docs/Usage/Exceptions.md
            // promises, rather than whatever the half-built tree happened to throw.
            //
            // Guarded on an error having been reported, so this cannot swallow a genuine bug:
            // where the parser throws with nothing recorded against the input, the exception
            // is ours and it keeps propagating.
            // https://github.com/asc-community/AngouriMath/issues/813
            try
            {
                parser.Parse();
            }
            catch (Exception) when (writer.errors.Count > 0)
            {
                return new Failure<ReasonWhyParsingFailed>(writer.errors[0]);
            }

            if (writer.errors.Count > 0)
                return new Failure<ReasonWhyParsingFailed>(writer.errors[0]);

            return RationalLiterals(parser.Result);
        }

        /// <summary>
        /// Rewrites a quotient of two integer literals into the <see cref="Rational"/> it denotes,
        /// so that a <see cref="Rational"/>'s printed form parses back to a
        /// <see cref="Rational"/>.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The rewrite itself is <see cref="Antlr.ParsingHelpers.RationalLiteral"/>, which the
        /// <c>domain(...)</c> rule also calls — on its argument, before annotating it. That is what
        /// lets this sweep hand back a bare <see cref="Rational"/> and read no codomain at all: a
        /// quotient reaching here has never been annotated, because the only syntax that annotates
        /// anything has already folded what it was given.
        /// </para>
        /// <para>
        /// Reading one would be wrong as well as unnecessary. An unannotated quotient carries the
        /// default, <see cref="Domain.Complex"/>, and a rational literal the tighter
        /// <see cref="Domain.Rational"/>, so copying it across would make <c>7/2</c> and <c>3.5</c>
        /// structurally unequal — the round trip this exists to fix, broken from the other end.
        /// Telling that default apart from a <c>domain(x, CC)</c> somebody wrote is what no reader
        /// of a finished tree can do, and it cost <c>domain(1/2, CC)</c> its annotation until
        /// the fold moved to where the annotation is applied.
        /// https://github.com/asc-community/AngouriMath/issues/1048
        /// </para>
        /// </remarks>
        private static Entity RationalLiterals(Entity parsed)
            => parsed.Replace(static node => Antlr.ParsingHelpers.RationalLiteral(node));

        internal static Entity Parse(string source)
            => ParseSilent(source)
                .Switch(
                    valid => valid,
                    // ANTLR's diagnostic is a line and a column and nothing else, which names
                    // no input once the string has travelled through a caller's own layers. The
                    // source is appended rather than prepended because the location is what the
                    // message is read for first, and because callers assert on that prefix.
                    failure => failure.Reason.Switch<Entity>(
                            unknown => throw new UnhandledParseException($"{unknown.Reason}, while parsing `{source}`"),
                            missingOperator => throw new MissingOperatorParseException($"{missingOperator.Details}, while parsing `{source}`"),
                            internalError => throw new AngouriBugException($"{internalError.Details}, while parsing `{source}`")
                    )
                );
    }
}