<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.fsproj'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
