//
// Copyright (c) 2019-2026 Angouri.
// AngouriMath is licensed under MIT.
// Details: https://github.com/asc-community/AngouriMath/blob/master/LICENSE.md.
// Website: https://am.angouri.org.
//

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Harness
{
    /// <summary>
    /// The findings a harness reports by design, committed beside it, so that a run fails when
    /// the list changes rather than whenever it is not empty.
    /// </summary>
    /// <remarks>
    /// A count that moves is not a finding, and a list that changes is. The shape is the one
    /// <c>Sources/Tests/UnitTests/Corpus/corpus-baseline.tsv</c> uses: a committed record, an
    /// environment variable that regenerates it, and a failure that spells out both directions.
    /// A finding that goes away fails the run as well as one that appears, as a prompt to record
    /// the change with the commit that made it.
    /// https://github.com/asc-community/AngouriMath/issues/1256
    /// </remarks>
    static class Baseline
    {
        /// <summary>Set to rewrite the committed list from this run instead of comparing with it.</summary>
        internal const string UpdateVariable = "HARNESS_UPDATE_BASELINE";

        /// <summary>How many lines of each direction a failing run prints.</summary>
        private const int Shown = 40;

        /// <summary>
        /// Compares this run's findings with the committed list and returns the exit code: 0 when
        /// they are the same, 1 when a finding appeared or one went away.
        /// </summary>
        /// <param name="file">The list's file name, in the harness's own project directory.</param>
        /// <param name="what">What one line of the list is, for the file's header.</param>
        /// <param name="findings">One line per finding, its fields separated by tabs.</param>
        /// <param name="unmeasured">
        /// Whether a committed finding that this run did not report went unmeasured, because its
        /// case timed out, rather than went away. Such a finding is reported and fails nothing,
        /// since a shared runner is slower than the machine a budget was set on.
        /// </param>
        internal static int Check(string file, string what, IEnumerable<string> findings, Func<string, bool> unmeasured)
        {
            var path = Path.Combine(ProjectDirectory(), file);
            var found = new SortedSet<string>(findings, StringComparer.Ordinal);

            if (!string.IsNullOrEmpty(Environment.GetEnvironmentVariable(UpdateVariable)))
            {
                File.WriteAllText(path, string.Join("\n", Header(what).Concat(found)) + "\n");
                Console.WriteLine($"Rewrote {path} with {found.Count} findings.");
                return 0;
            }
            if (!File.Exists(path))
            {
                Console.WriteLine($"{path} does not exist. Run with {UpdateVariable}=1 to write it.");
                return 1;
            }

            var recorded = new SortedSet<string>(
                File.ReadAllLines(path).Where(line => line.Length > 0 && !line.StartsWith("#", StringComparison.Ordinal)),
                StringComparer.Ordinal);
            var appeared = found.Where(line => !recorded.Contains(line)).ToList();
            var missing = recorded.Where(line => !found.Contains(line)).ToList();
            var gone = missing.Where(line => !unmeasured(line)).ToList();

            if (missing.Count > gone.Count)
                Console.WriteLine($"{missing.Count - gone.Count} findings in {file} went unmeasured: their cases timed out.");
            if (appeared.Count == 0 && gone.Count == 0)
            {
                Console.WriteLine($"The findings match {file}: {found.Count}.");
                return 0;
            }

            Console.WriteLine($"The findings differ from {file}: {appeared.Count} appeared, {gone.Count} went away.");
            Print("appeared", appeared);
            Print("went away", gone);
            Console.WriteLine($"If the change is intended, record it: run this with {UpdateVariable}=1 and commit {file} with it.");
            return 1;
        }

        private static void Print(string label, List<string> lines)
        {
            foreach (var line in lines.Take(Shown))
                Console.WriteLine($"  {label,-9}  {line}");
            if (lines.Count > Shown)
                Console.WriteLine($"  {label,-9}  ... and {lines.Count - Shown} more");
        }

        private static IEnumerable<string> Header(string what)
        {
            yield return $"# {what}";
            yield return "# One line per finding, tab separated, sorted. Generated by the harness, not edited by hand:";
            yield return $"# to update it, run the harness with {UpdateVariable}=1 and commit it with the change that moved it.";
        }

        /// <summary>
        /// The harness's own project directory, from the assembly rather than the working
        /// directory, which need not be anywhere near it.
        /// </summary>
        private static string ProjectDirectory()
            => Directory.GetParent(AppContext.BaseDirectory).Parent.Parent.Parent.FullName;

        /// <summary>One field of a line: a tab or a line break inside it would split the line.</summary>
        internal static string Field(string text)
            => text.Replace('\t', ' ').Replace('\r', ' ').Replace('\n', ' ');
    }
}
