//
// Copyright (c) 2019-2026 Angouri.
// AngouriMath is licensed under MIT.
// Details: https://github.com/asc-community/AngouriMath/blob/master/LICENSE.md.
// Website: https://am.angouri.org.
//

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace DocSamples;

enum Verdict { Ok, CompileError, Threw, Timeout, OutputMismatch, Unchecked, Compiled, Skipped }

sealed class Finding
{
    public Snippet Snippet;
    public Verdict Verdict;
    /// The compiler diagnostics, the exception, or the two outputs -- whatever says what went wrong.
    public string Detail = "";
    public string Actual = "";
}

static class Report
{
    public static void Write(string path, string wikiOrigin, string repository,
        List<Finding> findings, int unannotatedSiteBlocks = 0)
    {
        var sb = new StringBuilder();
        var counts = Enum.GetValues<Verdict>().ToDictionary(v => v, v => findings.Count(f => f.Verdict == v));

        sb.AppendLine("# Wiki code samples against the built library");
        sb.AppendLine();
        sb.AppendLine($"Measured against `{Harness.Measured.Commit(repository)}`.");
        sb.AppendLine();
        sb.AppendLine($"Generated by `Sources/Tests/Harnesses/DocSamples` from `{wikiOrigin}`.");
        sb.AppendLine();
        sb.AppendLine("Every `cs` and `fs` block in the wiki is compiled against the library in this "
                      + "checkout, and run where it can be. A sample that names an API the library "
                      + "no longer has is a compile error here rather than a bug report from a reader. "
                      + "A sample that does not finish is listed and fails nothing.");
        sb.AppendLine();
        sb.AppendLine("| | Samples |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| Total | {findings.Count} |");
        sb.AppendLine($"| Compiled, ran, output matches the page | {counts[Verdict.Ok]} |");
        sb.AppendLine($"| Compiled and ran, page states no output | {counts[Verdict.Unchecked]} |");
        sb.AppendLine($"| Compiled, not run by directive | {counts[Verdict.Compiled]} |");
        sb.AppendLine($"| **Compile error** | **{counts[Verdict.CompileError]}** |");
        sb.AppendLine($"| **Output differs from the page** | **{counts[Verdict.OutputMismatch]}** |");
        sb.AppendLine($"| **Threw** | **{counts[Verdict.Threw]}** |");
        sb.AppendLine($"| **Did not finish** | **{counts[Verdict.Timeout]}** |");
        sb.AppendLine($"| Not compiled by directive | {counts[Verdict.Skipped]} |");
        sb.AppendLine();
        if (unannotatedSiteBlocks > 0)
        {
            sb.AppendLine($"{unannotatedSiteBlocks} `pre code` blocks on the website's pages carry no "
                          + "`amcheck` annotation and are therefore **not** checked — most are shell, "
                          + "CMake or notebook lines rather than a program, but the count is here so "
                          + "that the coverage is not read as complete.");
            sb.AppendLine();
        }

        var bad = findings.Where(f => f.Verdict is Verdict.CompileError or Verdict.OutputMismatch
                                          or Verdict.Threw or Verdict.Timeout).ToList();
        if (bad.Count == 0)
        {
            sb.AppendLine("No sample fails to compile, and every stated output is the one produced.");
        }
        else
        {
            sb.AppendLine("## What is wrong");
            sb.AppendLine();
            foreach (var f in bad)
            {
                sb.AppendLine($"### `{f.Snippet.Where}` — {Describe(f.Verdict)}");
                sb.AppendLine();
                sb.AppendLine("```" + f.Snippet.Language);
                foreach (var line in f.Snippet.Body) sb.AppendLine(line);
                sb.AppendLine("```");
                sb.AppendLine();
                if (f.Verdict == Verdict.OutputMismatch)
                {
                    sb.AppendLine("The page says:");
                    sb.AppendLine();
                    sb.AppendLine("```");
                    sb.AppendLine(f.Snippet.Expected);
                    sb.AppendLine("```");
                    sb.AppendLine();
                    sb.AppendLine("It prints:");
                    sb.AppendLine();
                    sb.AppendLine("```");
                    sb.AppendLine(f.Actual.TrimEnd('\n'));
                    sb.AppendLine("```");
                }
                else
                {
                    sb.AppendLine("```");
                    sb.AppendLine(f.Detail.TrimEnd('\n'));
                    sb.AppendLine("```");
                }
                sb.AppendLine();
            }
        }

        var skipped = findings.Where(f => f.Verdict is Verdict.Skipped or Verdict.Compiled).ToList();
        if (skipped.Count > 0)
        {
            sb.AppendLine("## Not checked in full, and why");
            sb.AppendLine();
            sb.AppendLine("| Sample | Treatment | Reason |");
            sb.AppendLine("|---|---|---|");
            foreach (var f in skipped)
                sb.AppendLine($"| `{f.Snippet.Where}` | "
                              + (f.Verdict == Verdict.Skipped ? "not compiled" : "compiled, not run")
                              + $" | {(f.Snippet.Reason.Length == 0 ? "—" : f.Snippet.Reason)} |");
            sb.AppendLine();
        }

        File.WriteAllText(path, sb.ToString());
    }

    static string Describe(Verdict v) => v switch
    {
        Verdict.CompileError => "does not compile",
        Verdict.OutputMismatch => "prints something else",
        Verdict.Threw => "throws",
        Verdict.Timeout => "does not finish",
        _ => v.ToString(),
    };
}
