//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./AngouriMath.g by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AngouriMath.Core.Antlr {

    using System.Linq;
    using AngouriMath;
    using static AngouriMath.Core.Exceptions.FunctionArgumentCountException;
    using static AngouriMath.Entity.Number;
    using AngouriMath.Core.Exceptions;
    using static AngouriMath.Entity.Set;

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
internal partial class AngouriMathParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, T__41=42, T__42=43, T__43=44, T__44=45, 
		T__45=46, T__46=47, T__47=48, T__48=49, T__49=50, T__50=51, T__51=52, 
		T__52=53, T__53=54, T__54=55, T__55=56, T__56=57, T__57=58, NEWLINE=59, 
		NUMBER=60, BOOLEAN=61, VARIABLE=62, COMMENT=63, WS=64;
	public const int
		RULE_factorial_expression = 0, RULE_power_list = 1, RULE_power_expression = 2, 
		RULE_unary_expression = 3, RULE_mult_expression = 4, RULE_sum_expression = 5, 
		RULE_inequality_expression = 6, RULE_equality_expression = 7, RULE_negate_expression = 8, 
		RULE_and_expression = 9, RULE_xor_expression = 10, RULE_or_expression = 11, 
		RULE_implies_expression = 12, RULE_expression = 13, RULE_function_arguments = 14, 
		RULE_interval_arguments = 15, RULE_atom = 16, RULE_statement = 17;
	public static readonly string[] ruleNames = {
		"factorial_expression", "power_list", "power_expression", "unary_expression", 
		"mult_expression", "sum_expression", "inequality_expression", "equality_expression", 
		"negate_expression", "and_expression", "xor_expression", "or_expression", 
		"implies_expression", "expression", "function_arguments", "interval_arguments", 
		"atom", "statement"
	};

	private static readonly string[] _LiteralNames = {
		null, "'!'", "'^'", "'-'", "'+'", "'*'", "'/'", "'>='", "'<='", "'>'", 
		"'<'", "'equalizes'", "'='", "'not'", "'and'", "'&'", "'xor'", "'or'", 
		"'|'", "'implies'", "'->'", "','", "';'", "'(|'", "'|)'", "'('", "')'", 
		"'['", "']'", "'{'", "'}'", "'sin('", "'cos('", "'log('", "'sqrt('", "'cbrt('", 
		"'sqr('", "'ln('", "'tan('", "'cotan('", "'sec('", "'cosec('", "'arcsin('", 
		"'arccos('", "'arctan('", "'arccotan('", "'arcsec('", "'arccosec('", "'gamma('", 
		"'derivative('", "'integral('", "'limit('", "'limitleft('", "'limitright('", 
		"'signum('", "'sgn('", "'sign('", "'abs('", "'domain('"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, "NEWLINE", 
		"NUMBER", "BOOLEAN", "VARIABLE", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "AngouriMath.g"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static AngouriMathParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}


	    // Nullable reference type analysis is disabled by default for generated code without '#nullable enable'
	    public Entity Result = null;
	    
	    public void Parse() { this.statement(); }

		public AngouriMathParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public AngouriMathParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	internal partial class Factorial_expressionContext : ParserRuleContext {
		public Entity value;
		public AtomContext p;
		public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public Factorial_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_factorial_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterFactorial_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitFactorial_expression(this);
		}
	}

	[RuleVersion(0)]
	public Factorial_expressionContext factorial_expression() {
		Factorial_expressionContext _localctx = new Factorial_expressionContext(Context, State);
		EnterRule(_localctx, 0, RULE_factorial_expression);
		try {
			State = 43;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 36; _localctx.p = atom();
				State = 37; Match(T__0);
				 _localctx.value =  MathS.Factorial(_localctx.p.value); 
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 40; _localctx.p = atom();
				 _localctx.value =  _localctx.p.value; 
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Power_listContext : ParserRuleContext {
		public List<Entity> value;
		public Factorial_expressionContext _factorial_expression;
		public Factorial_expressionContext[] factorial_expression() {
			return GetRuleContexts<Factorial_expressionContext>();
		}
		public Factorial_expressionContext factorial_expression(int i) {
			return GetRuleContext<Factorial_expressionContext>(i);
		}
		public Power_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_power_list; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterPower_list(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitPower_list(this);
		}
	}

	[RuleVersion(0)]
	public Power_listContext power_list() {
		Power_listContext _localctx = new Power_listContext(Context, State);
		EnterRule(_localctx, 2, RULE_power_list);
		 _localctx.value =  new List<Entity>(); 
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 49;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 45; Match(T__1);
				State = 46; _localctx._factorial_expression = factorial_expression();
				 _localctx.value.Add(_localctx._factorial_expression.value); 
				}
				}
				State = 51;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__1 );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Power_expressionContext : ParserRuleContext {
		public Entity value;
		public Factorial_expressionContext _factorial_expression;
		public Power_listContext _power_list;
		public Factorial_expressionContext factorial_expression() {
			return GetRuleContext<Factorial_expressionContext>(0);
		}
		public Power_listContext power_list() {
			return GetRuleContext<Power_listContext>(0);
		}
		public Power_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_power_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterPower_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitPower_expression(this);
		}
	}

	[RuleVersion(0)]
	public Power_expressionContext power_expression() {
		Power_expressionContext _localctx = new Power_expressionContext(Context, State);
		EnterRule(_localctx, 4, RULE_power_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53; _localctx._factorial_expression = factorial_expression();
			 _localctx.value =  _localctx._factorial_expression.value; 
			State = 58;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__1) {
				{
				State = 55; _localctx._power_list = power_list();

				        var list = _localctx._power_list.value;
				        _localctx.value =  list.Last();
				        list.RemoveAt(list.Count - 1);
				        list.Reverse(); 
				        list.Add(_localctx._factorial_expression.value);
				        foreach(var p in list) { _localctx.value =  MathS.Pow(p, _localctx.value); }
				    
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Unary_expressionContext : ParserRuleContext {
		public Entity value;
		public Power_expressionContext p;
		public Unary_expressionContext u;
		public Power_expressionContext power_expression() {
			return GetRuleContext<Power_expressionContext>(0);
		}
		public Unary_expressionContext unary_expression() {
			return GetRuleContext<Unary_expressionContext>(0);
		}
		public Unary_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unary_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterUnary_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitUnary_expression(this);
		}
	}

	[RuleVersion(0)]
	public Unary_expressionContext unary_expression() {
		Unary_expressionContext _localctx = new Unary_expressionContext(Context, State);
		EnterRule(_localctx, 6, RULE_unary_expression);
		try {
			State = 83;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 68;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__2:
					{
					State = 60; Match(T__2);
					State = 61; _localctx.p = power_expression();
					 _localctx.value =  -_localctx.p.value; 
					}
					break;
				case T__3:
					{
					State = 64; Match(T__3);
					State = 65; _localctx.p = power_expression();
					 _localctx.value =  _localctx.p.value; 
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 78;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__2:
					{
					State = 70; Match(T__2);
					State = 71; _localctx.u = unary_expression();
					 _localctx.value =  -_localctx.u.value; 
					}
					break;
				case T__3:
					{
					State = 74; Match(T__3);
					State = 75; _localctx.u = unary_expression();
					 _localctx.value =  _localctx.u.value; 
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 80; _localctx.p = power_expression();
				 _localctx.value =  _localctx.p.value; 
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Mult_expressionContext : ParserRuleContext {
		public Entity value;
		public Unary_expressionContext u1;
		public Unary_expressionContext u2;
		public Unary_expressionContext[] unary_expression() {
			return GetRuleContexts<Unary_expressionContext>();
		}
		public Unary_expressionContext unary_expression(int i) {
			return GetRuleContext<Unary_expressionContext>(i);
		}
		public Mult_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mult_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterMult_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitMult_expression(this);
		}
	}

	[RuleVersion(0)]
	public Mult_expressionContext mult_expression() {
		Mult_expressionContext _localctx = new Mult_expressionContext(Context, State);
		EnterRule(_localctx, 8, RULE_mult_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 85; _localctx.u1 = unary_expression();
			 _localctx.value =  _localctx.u1.value; 
			State = 97;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4 || _la==T__5) {
				{
				State = 95;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__4:
					{
					State = 87; Match(T__4);
					State = 88; _localctx.u2 = unary_expression();
					 _localctx.value =  _localctx.value * _localctx.u2.value; 
					}
					break;
				case T__5:
					{
					State = 91; Match(T__5);
					State = 92; _localctx.u2 = unary_expression();
					 _localctx.value =  _localctx.value / _localctx.u2.value; 
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 99;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Sum_expressionContext : ParserRuleContext {
		public Entity value;
		public Mult_expressionContext m1;
		public Mult_expressionContext m2;
		public Mult_expressionContext[] mult_expression() {
			return GetRuleContexts<Mult_expressionContext>();
		}
		public Mult_expressionContext mult_expression(int i) {
			return GetRuleContext<Mult_expressionContext>(i);
		}
		public Sum_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sum_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterSum_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitSum_expression(this);
		}
	}

	[RuleVersion(0)]
	public Sum_expressionContext sum_expression() {
		Sum_expressionContext _localctx = new Sum_expressionContext(Context, State);
		EnterRule(_localctx, 10, RULE_sum_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100; _localctx.m1 = mult_expression();
			 _localctx.value =  _localctx.m1.value; 
			State = 112;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__2 || _la==T__3) {
				{
				State = 110;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__3:
					{
					State = 102; Match(T__3);
					State = 103; _localctx.m2 = mult_expression();
					 _localctx.value =  _localctx.value + _localctx.m2.value; 
					}
					break;
				case T__2:
					{
					State = 106; Match(T__2);
					State = 107; _localctx.m2 = mult_expression();
					 _localctx.value =  _localctx.value - _localctx.m2.value; 
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 114;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Inequality_expressionContext : ParserRuleContext {
		public Entity value;
		public Sum_expressionContext m1;
		public Sum_expressionContext m2;
		public Sum_expressionContext[] sum_expression() {
			return GetRuleContexts<Sum_expressionContext>();
		}
		public Sum_expressionContext sum_expression(int i) {
			return GetRuleContext<Sum_expressionContext>(i);
		}
		public Inequality_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_inequality_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterInequality_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitInequality_expression(this);
		}
	}

	[RuleVersion(0)]
	public Inequality_expressionContext inequality_expression() {
		Inequality_expressionContext _localctx = new Inequality_expressionContext(Context, State);
		EnterRule(_localctx, 12, RULE_inequality_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 115; _localctx.m1 = sum_expression();
			 _localctx.value =  _localctx.m1.value; 
			State = 139;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__6) | (1L << T__7) | (1L << T__8) | (1L << T__9) | (1L << T__10))) != 0)) {
				{
				State = 137;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__6:
					{
					State = 117; Match(T__6);
					State = 118; _localctx.m2 = sum_expression();
					 _localctx.value =  _localctx.value >= _localctx.m2.value; 
					}
					break;
				case T__7:
					{
					State = 121; Match(T__7);
					State = 122; _localctx.m2 = sum_expression();
					 _localctx.value =  _localctx.value <= _localctx.m2.value; 
					}
					break;
				case T__8:
					{
					State = 125; Match(T__8);
					State = 126; _localctx.m2 = sum_expression();
					 _localctx.value =  _localctx.value > _localctx.m2.value; 
					}
					break;
				case T__9:
					{
					State = 129; Match(T__9);
					State = 130; _localctx.m2 = sum_expression();
					 _localctx.value =  _localctx.value < _localctx.m2.value; 
					}
					break;
				case T__10:
					{
					State = 133; Match(T__10);
					State = 134; _localctx.m2 = sum_expression();
					 _localctx.value =  MathS.Equality(_localctx.value, _localctx.m2.value); 
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 141;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Equality_expressionContext : ParserRuleContext {
		public Entity value;
		public Inequality_expressionContext m1;
		public Inequality_expressionContext m2;
		public Inequality_expressionContext[] inequality_expression() {
			return GetRuleContexts<Inequality_expressionContext>();
		}
		public Inequality_expressionContext inequality_expression(int i) {
			return GetRuleContext<Inequality_expressionContext>(i);
		}
		public Equality_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_equality_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterEquality_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitEquality_expression(this);
		}
	}

	[RuleVersion(0)]
	public Equality_expressionContext equality_expression() {
		Equality_expressionContext _localctx = new Equality_expressionContext(Context, State);
		EnterRule(_localctx, 14, RULE_equality_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 142; _localctx.m1 = inequality_expression();
			 _localctx.value =  _localctx.m1.value; 
			State = 150;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__11) {
				{
				{
				State = 144; Match(T__11);
				State = 145; _localctx.m2 = inequality_expression();
				 _localctx.value =  _localctx.value.Equalizes(_localctx.m2.value); 
				}
				}
				State = 152;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Negate_expressionContext : ParserRuleContext {
		public Entity value;
		public Equality_expressionContext _equality_expression;
		public Negate_expressionContext _negate_expression;
		public Equality_expressionContext equality_expression() {
			return GetRuleContext<Equality_expressionContext>(0);
		}
		public Negate_expressionContext negate_expression() {
			return GetRuleContext<Negate_expressionContext>(0);
		}
		public Negate_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_negate_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterNegate_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitNegate_expression(this);
		}
	}

	[RuleVersion(0)]
	public Negate_expressionContext negate_expression() {
		Negate_expressionContext _localctx = new Negate_expressionContext(Context, State);
		EnterRule(_localctx, 16, RULE_negate_expression);
		try {
			State = 164;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 153; Match(T__12);
				State = 154; _localctx._equality_expression = equality_expression();
				 _localctx.value =  !_localctx._equality_expression.value; 
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 157; Match(T__12);
				State = 158; _localctx._negate_expression = negate_expression();
				 _localctx.value =  !_localctx._negate_expression.value; 
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 161; _localctx._equality_expression = equality_expression();
				 _localctx.value =  _localctx._equality_expression.value; 
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class And_expressionContext : ParserRuleContext {
		public Entity value;
		public Negate_expressionContext m1;
		public Negate_expressionContext m2;
		public Negate_expressionContext[] negate_expression() {
			return GetRuleContexts<Negate_expressionContext>();
		}
		public Negate_expressionContext negate_expression(int i) {
			return GetRuleContext<Negate_expressionContext>(i);
		}
		public And_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_and_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterAnd_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitAnd_expression(this);
		}
	}

	[RuleVersion(0)]
	public And_expressionContext and_expression() {
		And_expressionContext _localctx = new And_expressionContext(Context, State);
		EnterRule(_localctx, 18, RULE_and_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 166; _localctx.m1 = negate_expression();
			 _localctx.value =  _localctx.m1.value; 
			State = 178;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__13 || _la==T__14) {
				{
				State = 176;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__13:
					{
					State = 168; Match(T__13);
					State = 169; _localctx.m2 = negate_expression();
					 _localctx.value =  _localctx.value & _localctx.m2.value; 
					}
					break;
				case T__14:
					{
					State = 172; Match(T__14);
					State = 173; _localctx.m2 = negate_expression();
					 _localctx.value =  _localctx.value & _localctx.m2.value; 
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 180;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Xor_expressionContext : ParserRuleContext {
		public Entity value;
		public And_expressionContext m1;
		public And_expressionContext m2;
		public And_expressionContext[] and_expression() {
			return GetRuleContexts<And_expressionContext>();
		}
		public And_expressionContext and_expression(int i) {
			return GetRuleContext<And_expressionContext>(i);
		}
		public Xor_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_xor_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterXor_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitXor_expression(this);
		}
	}

	[RuleVersion(0)]
	public Xor_expressionContext xor_expression() {
		Xor_expressionContext _localctx = new Xor_expressionContext(Context, State);
		EnterRule(_localctx, 20, RULE_xor_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 181; _localctx.m1 = and_expression();
			 _localctx.value =  _localctx.m1.value; 
			State = 189;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__15) {
				{
				{
				State = 183; Match(T__15);
				State = 184; _localctx.m2 = and_expression();
				 _localctx.value =  _localctx.value ^ _localctx.m2.value; 
				}
				}
				State = 191;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Or_expressionContext : ParserRuleContext {
		public Entity value;
		public Xor_expressionContext m1;
		public Xor_expressionContext m2;
		public Xor_expressionContext[] xor_expression() {
			return GetRuleContexts<Xor_expressionContext>();
		}
		public Xor_expressionContext xor_expression(int i) {
			return GetRuleContext<Xor_expressionContext>(i);
		}
		public Or_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_or_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterOr_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitOr_expression(this);
		}
	}

	[RuleVersion(0)]
	public Or_expressionContext or_expression() {
		Or_expressionContext _localctx = new Or_expressionContext(Context, State);
		EnterRule(_localctx, 22, RULE_or_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 192; _localctx.m1 = xor_expression();
			 _localctx.value =  _localctx.m1.value; 
			State = 204;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__16 || _la==T__17) {
				{
				State = 202;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__16:
					{
					State = 194; Match(T__16);
					State = 195; _localctx.m2 = xor_expression();
					 _localctx.value =  _localctx.value | _localctx.m2.value; 
					}
					break;
				case T__17:
					{
					State = 198; Match(T__17);
					State = 199; _localctx.m2 = xor_expression();
					 _localctx.value =  _localctx.value | _localctx.m2.value; 
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 206;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Implies_expressionContext : ParserRuleContext {
		public Entity value;
		public Or_expressionContext m1;
		public Or_expressionContext m2;
		public Or_expressionContext[] or_expression() {
			return GetRuleContexts<Or_expressionContext>();
		}
		public Or_expressionContext or_expression(int i) {
			return GetRuleContext<Or_expressionContext>(i);
		}
		public Implies_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_implies_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterImplies_expression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitImplies_expression(this);
		}
	}

	[RuleVersion(0)]
	public Implies_expressionContext implies_expression() {
		Implies_expressionContext _localctx = new Implies_expressionContext(Context, State);
		EnterRule(_localctx, 24, RULE_implies_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 207; _localctx.m1 = or_expression();
			 _localctx.value =  _localctx.m1.value; 
			State = 219;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__18 || _la==T__19) {
				{
				State = 217;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__18:
					{
					State = 209; Match(T__18);
					State = 210; _localctx.m2 = or_expression();
					 _localctx.value =  _localctx.value.Implies(_localctx.m2.value); 
					}
					break;
				case T__19:
					{
					State = 213; Match(T__19);
					State = 214; _localctx.m2 = or_expression();
					 _localctx.value =  _localctx.value.Implies(_localctx.m2.value); 
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 221;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class ExpressionContext : ParserRuleContext {
		public Entity value;
		public Implies_expressionContext s;
		public Implies_expressionContext implies_expression() {
			return GetRuleContext<Implies_expressionContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 26, RULE_expression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 222; _localctx.s = implies_expression();
			 _localctx.value =  _localctx.s.value; 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Function_argumentsContext : ParserRuleContext {
		public List<Entity> list;
		public ExpressionContext e;
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Function_argumentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_arguments; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterFunction_arguments(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitFunction_arguments(this);
		}
	}

	[RuleVersion(0)]
	public Function_argumentsContext function_arguments() {
		Function_argumentsContext _localctx = new Function_argumentsContext(Context, State);
		EnterRule(_localctx, 28, RULE_function_arguments);
		 _localctx.list =  new List<Entity>(); 
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 236;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__2) | (1L << T__3) | (1L << T__12) | (1L << T__22) | (1L << T__24) | (1L << T__26) | (1L << T__28) | (1L << T__30) | (1L << T__31) | (1L << T__32) | (1L << T__33) | (1L << T__34) | (1L << T__35) | (1L << T__36) | (1L << T__37) | (1L << T__38) | (1L << T__39) | (1L << T__40) | (1L << T__41) | (1L << T__42) | (1L << T__43) | (1L << T__44) | (1L << T__45) | (1L << T__46) | (1L << T__47) | (1L << T__48) | (1L << T__49) | (1L << T__50) | (1L << T__51) | (1L << T__52) | (1L << T__53) | (1L << T__54) | (1L << T__55) | (1L << T__56) | (1L << T__57) | (1L << NUMBER) | (1L << BOOLEAN) | (1L << VARIABLE))) != 0)) {
				{
				State = 225; _localctx.e = expression();
				 _localctx.list.Add(_localctx.e.value); 
				State = 233;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__20) {
					{
					{
					State = 227; Match(T__20);
					State = 228; _localctx.e = expression();
					 _localctx.list.Add(_localctx.e.value); 
					}
					}
					State = 235;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class Interval_argumentsContext : ParserRuleContext {
		public (Entity from, Entity to) couple;
		public ExpressionContext from;
		public ExpressionContext to;
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Interval_argumentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interval_arguments; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterInterval_arguments(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitInterval_arguments(this);
		}
	}

	[RuleVersion(0)]
	public Interval_argumentsContext interval_arguments() {
		Interval_argumentsContext _localctx = new Interval_argumentsContext(Context, State);
		EnterRule(_localctx, 30, RULE_interval_arguments);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 238; _localctx.from = expression();
			 _localctx.couple.from = _localctx.from.value; 
			State = 240; Match(T__21);
			State = 241; _localctx.to = expression();
			 _localctx.couple.to = _localctx.to.value; 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class AtomContext : ParserRuleContext {
		public Entity value;
		public IToken _NUMBER;
		public IToken _BOOLEAN;
		public IToken _VARIABLE;
		public ExpressionContext _expression;
		public Interval_argumentsContext _interval_arguments;
		public Function_argumentsContext args;
		public ITerminalNode NUMBER() { return GetToken(AngouriMathParser.NUMBER, 0); }
		public ITerminalNode BOOLEAN() { return GetToken(AngouriMathParser.BOOLEAN, 0); }
		public ITerminalNode VARIABLE() { return GetToken(AngouriMathParser.VARIABLE, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Interval_argumentsContext interval_arguments() {
			return GetRuleContext<Interval_argumentsContext>(0);
		}
		public Function_argumentsContext function_arguments() {
			return GetRuleContext<Function_argumentsContext>(0);
		}
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitAtom(this);
		}
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 32, RULE_atom);
		try {
			State = 425;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,23,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 244; _localctx._NUMBER = Match(NUMBER);
				 _localctx.value =  Entity.Number.Complex.Parse((_localctx._NUMBER!=null?_localctx._NUMBER.Text:null)); 
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 246; _localctx._BOOLEAN = Match(BOOLEAN);
				 _localctx.value =  Entity.Boolean.Parse((_localctx._BOOLEAN!=null?_localctx._BOOLEAN.Text:null)); 
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 248; _localctx._VARIABLE = Match(VARIABLE);
				 _localctx.value =  Entity.Variable.CreateVariableUnchecked((_localctx._VARIABLE!=null?_localctx._VARIABLE.Text:null)); 
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 250; Match(T__22);
				State = 251; _localctx._expression = expression();
				State = 252; Match(T__23);
				 _localctx.value =  _localctx._expression.value.Abs(); 
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 255; Match(T__24);
				State = 256; _localctx._interval_arguments = interval_arguments();
				State = 257; Match(T__25);
				 _localctx.value =  new Entity.Set.Interval(_localctx._interval_arguments.couple.from, false, _localctx._interval_arguments.couple.to, false); 
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 260; Match(T__26);
				State = 261; _localctx._interval_arguments = interval_arguments();
				State = 262; Match(T__25);
				 _localctx.value =  new Entity.Set.Interval(_localctx._interval_arguments.couple.from, true, _localctx._interval_arguments.couple.to, false); 
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 265; Match(T__26);
				State = 266; _localctx._interval_arguments = interval_arguments();
				State = 267; Match(T__27);
				 _localctx.value =  new Entity.Set.Interval(_localctx._interval_arguments.couple.from, true, _localctx._interval_arguments.couple.to, true); 
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 270; Match(T__26);
				State = 271; _localctx._interval_arguments = interval_arguments();
				State = 272; Match(T__27);
				 _localctx.value =  new Entity.Set.Interval(_localctx._interval_arguments.couple.from, true, _localctx._interval_arguments.couple.to, true); 
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 275; Match(T__24);
				State = 276; _localctx._expression = expression();
				State = 277; Match(T__25);
				 _localctx.value =  _localctx._expression.value; 
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 280; Match(T__28);
				State = 281; _localctx.args = function_arguments();
				State = 282; Match(T__29);
				 _localctx.value =  new FiniteSet((IEnumerable<Entity>)_localctx.args.list); 
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 285; Match(T__30);
				State = 286; _localctx.args = function_arguments();
				State = 287; Match(T__25);
				 Assert("sin", 1, _localctx.args.list.Count); _localctx.value =  MathS.Sin(_localctx.args.list[0]); 
				}
				break;
			case 12:
				EnterOuterAlt(_localctx, 12);
				{
				State = 290; Match(T__31);
				State = 291; _localctx.args = function_arguments();
				State = 292; Match(T__25);
				 Assert("cos", 1, _localctx.args.list.Count); _localctx.value =  MathS.Cos(_localctx.args.list[0]); 
				}
				break;
			case 13:
				EnterOuterAlt(_localctx, 13);
				{
				State = 295; Match(T__32);
				State = 296; _localctx.args = function_arguments();
				State = 297; Match(T__25);
				 _localctx.value =  Assert("log", (1, 2), _localctx.args.list.Count) ? MathS.Log(10, _localctx.args.list[0]) : MathS.Log(_localctx.args.list[0], _localctx.args.list[1]); 
				}
				break;
			case 14:
				EnterOuterAlt(_localctx, 14);
				{
				State = 300; Match(T__33);
				State = 301; _localctx.args = function_arguments();
				State = 302; Match(T__25);
				 Assert("sqrt", 1, _localctx.args.list.Count); _localctx.value =  MathS.Sqrt(_localctx.args.list[0]); 
				}
				break;
			case 15:
				EnterOuterAlt(_localctx, 15);
				{
				State = 305; Match(T__34);
				State = 306; _localctx.args = function_arguments();
				State = 307; Match(T__25);
				 Assert("cbrt", 1, _localctx.args.list.Count); _localctx.value =  MathS.Cbrt(_localctx.args.list[0]); 
				}
				break;
			case 16:
				EnterOuterAlt(_localctx, 16);
				{
				State = 310; Match(T__35);
				State = 311; _localctx.args = function_arguments();
				State = 312; Match(T__25);
				 Assert("sqr", 1, _localctx.args.list.Count); _localctx.value =  MathS.Sqr(_localctx.args.list[0]); 
				}
				break;
			case 17:
				EnterOuterAlt(_localctx, 17);
				{
				State = 315; Match(T__36);
				State = 316; _localctx.args = function_arguments();
				State = 317; Match(T__25);
				 Assert("ln", 1, _localctx.args.list.Count); _localctx.value =  MathS.Ln(_localctx.args.list[0]); 
				}
				break;
			case 18:
				EnterOuterAlt(_localctx, 18);
				{
				State = 320; Match(T__37);
				State = 321; _localctx.args = function_arguments();
				State = 322; Match(T__25);
				 Assert("tan", 1, _localctx.args.list.Count); _localctx.value =  MathS.Tan(_localctx.args.list[0]); 
				}
				break;
			case 19:
				EnterOuterAlt(_localctx, 19);
				{
				State = 325; Match(T__38);
				State = 326; _localctx.args = function_arguments();
				State = 327; Match(T__25);
				 Assert("cotan", 1, _localctx.args.list.Count); _localctx.value =  MathS.Cotan(_localctx.args.list[0]); 
				}
				break;
			case 20:
				EnterOuterAlt(_localctx, 20);
				{
				State = 330; Match(T__39);
				State = 331; _localctx.args = function_arguments();
				State = 332; Match(T__25);
				 Assert("sec", 1, _localctx.args.list.Count); _localctx.value =  MathS.Sec(_localctx.args.list[0]); 
				}
				break;
			case 21:
				EnterOuterAlt(_localctx, 21);
				{
				State = 335; Match(T__40);
				State = 336; _localctx.args = function_arguments();
				State = 337; Match(T__25);
				 Assert("cosec", 1, _localctx.args.list.Count); _localctx.value =  MathS.Cosec(_localctx.args.list[0]); 
				}
				break;
			case 22:
				EnterOuterAlt(_localctx, 22);
				{
				State = 340; Match(T__41);
				State = 341; _localctx.args = function_arguments();
				State = 342; Match(T__25);
				 Assert("arcsin", 1, _localctx.args.list.Count); _localctx.value =  MathS.Arcsin(_localctx.args.list[0]); 
				}
				break;
			case 23:
				EnterOuterAlt(_localctx, 23);
				{
				State = 345; Match(T__42);
				State = 346; _localctx.args = function_arguments();
				State = 347; Match(T__25);
				 Assert("arccos", 1, _localctx.args.list.Count); _localctx.value =  MathS.Arccos(_localctx.args.list[0]); 
				}
				break;
			case 24:
				EnterOuterAlt(_localctx, 24);
				{
				State = 350; Match(T__43);
				State = 351; _localctx.args = function_arguments();
				State = 352; Match(T__25);
				 Assert("arctan", 1, _localctx.args.list.Count); _localctx.value =  MathS.Arctan(_localctx.args.list[0]); 
				}
				break;
			case 25:
				EnterOuterAlt(_localctx, 25);
				{
				State = 355; Match(T__44);
				State = 356; _localctx.args = function_arguments();
				State = 357; Match(T__25);
				 Assert("arccotan", 1, _localctx.args.list.Count); _localctx.value =  MathS.Arccotan(_localctx.args.list[0]); 
				}
				break;
			case 26:
				EnterOuterAlt(_localctx, 26);
				{
				State = 360; Match(T__45);
				State = 361; _localctx.args = function_arguments();
				State = 362; Match(T__25);
				 Assert("arcsec", 1, _localctx.args.list.Count); _localctx.value =  MathS.Arcsec(_localctx.args.list[0]); 
				}
				break;
			case 27:
				EnterOuterAlt(_localctx, 27);
				{
				State = 365; Match(T__46);
				State = 366; _localctx.args = function_arguments();
				State = 367; Match(T__25);
				 Assert("arccosec", 1, _localctx.args.list.Count); _localctx.value =  MathS.Arccosec(_localctx.args.list[0]); 
				}
				break;
			case 28:
				EnterOuterAlt(_localctx, 28);
				{
				State = 370; Match(T__47);
				State = 371; _localctx.args = function_arguments();
				State = 372; Match(T__25);
				 Assert("gamma", 1, _localctx.args.list.Count); _localctx.value =  MathS.Gamma(_localctx.args.list[0]); 
				}
				break;
			case 29:
				EnterOuterAlt(_localctx, 29);
				{
				State = 375; Match(T__48);
				State = 376; _localctx.args = function_arguments();
				State = 377; Match(T__25);
				 
				            Assert("derivative", 3, _localctx.args.list.Count); 
				            if (_localctx.args.list[2] is Integer { EInteger: var asEInt })
				                _localctx.value =  MathS.Derivative(_localctx.args.list[0], _localctx.args.list[1], asEInt.ToInt32Checked());
				            else
				                throw new ParseException("Expected number for the third argument of derivative");
				        
				}
				break;
			case 30:
				EnterOuterAlt(_localctx, 30);
				{
				State = 380; Match(T__49);
				State = 381; _localctx.args = function_arguments();
				State = 382; Match(T__25);
				 
				            Assert("integral", 3, _localctx.args.list.Count); 
				            if (_localctx.args.list[2] is Integer { EInteger: var asEInt })
				                _localctx.value =  MathS.Integral(_localctx.args.list[0], _localctx.args.list[1], asEInt.ToInt32Checked());
				            else
				                throw new ParseException("Expected number for the third argument of integral");
				        
				}
				break;
			case 31:
				EnterOuterAlt(_localctx, 31);
				{
				State = 385; Match(T__50);
				State = 386; _localctx.args = function_arguments();
				State = 387; Match(T__25);
				 Assert("limit", 3, _localctx.args.list.Count); _localctx.value =  MathS.Limit(_localctx.args.list[0], _localctx.args.list[1], _localctx.args.list[2]); 
				}
				break;
			case 32:
				EnterOuterAlt(_localctx, 32);
				{
				State = 390; Match(T__51);
				State = 391; _localctx.args = function_arguments();
				State = 392; Match(T__25);
				 Assert("limitleft", 3, _localctx.args.list.Count); _localctx.value =  MathS.Limit(_localctx.args.list[0], _localctx.args.list[1], _localctx.args.list[2], AngouriMath.Core.ApproachFrom.Left); 
				}
				break;
			case 33:
				EnterOuterAlt(_localctx, 33);
				{
				State = 395; Match(T__52);
				State = 396; _localctx.args = function_arguments();
				State = 397; Match(T__25);
				 Assert("limitright", 3, _localctx.args.list.Count); _localctx.value =  MathS.Limit(_localctx.args.list[0], _localctx.args.list[1], _localctx.args.list[2], AngouriMath.Core.ApproachFrom.Right); 
				}
				break;
			case 34:
				EnterOuterAlt(_localctx, 34);
				{
				State = 400; Match(T__53);
				State = 401; _localctx.args = function_arguments();
				State = 402; Match(T__25);
				 Assert("signum", 1, _localctx.args.list.Count); _localctx.value =  MathS.Signum(_localctx.args.list[0]); 
				}
				break;
			case 35:
				EnterOuterAlt(_localctx, 35);
				{
				State = 405; Match(T__54);
				State = 406; _localctx.args = function_arguments();
				State = 407; Match(T__25);
				 Assert("sgn", 1, _localctx.args.list.Count); _localctx.value =  MathS.Signum(_localctx.args.list[0]); 
				}
				break;
			case 36:
				EnterOuterAlt(_localctx, 36);
				{
				State = 410; Match(T__55);
				State = 411; _localctx.args = function_arguments();
				State = 412; Match(T__25);
				 Assert("sign", 1, _localctx.args.list.Count); _localctx.value =  MathS.Signum(_localctx.args.list[0]); 
				}
				break;
			case 37:
				EnterOuterAlt(_localctx, 37);
				{
				State = 415; Match(T__56);
				State = 416; _localctx.args = function_arguments();
				State = 417; Match(T__25);
				 Assert("abs", 1, _localctx.args.list.Count); _localctx.value =  MathS.Abs(_localctx.args.list[0]); 
				}
				break;
			case 38:
				EnterOuterAlt(_localctx, 38);
				{
				State = 420; Match(T__57);
				State = 421; _localctx.args = function_arguments();
				State = 422; Match(T__25);
				 Assert("domain", 2, _localctx.args.list.Count); _localctx.value =  _localctx.args.list[0].WithCodomain(DomainsFunctional.Parse(_localctx.args.list[1])); 
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class StatementContext : ParserRuleContext {
		public ExpressionContext _expression;
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(AngouriMathParser.Eof, 0); }
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IAngouriMathListener typedListener = listener as IAngouriMathListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 34, RULE_statement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 427; _localctx._expression = expression();
			State = 428; Match(Eof);
			 Result = _localctx._expression.value; 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x42', '\x1B2', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x5', '\x2', '.', '\n', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x6', '\x3', '\x34', 
		'\n', '\x3', '\r', '\x3', '\xE', '\x3', '\x35', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '=', '\n', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 'G', '\n', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 'Q', '\n', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 'V', '\n', '\x5', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\a', '\x6', '\x62', '\n', '\x6', '\f', '\x6', '\xE', '\x6', '\x65', '\v', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\a', 
		'\a', 'q', '\n', '\a', '\f', '\a', '\xE', '\a', 't', '\v', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\a', 
		'\b', '\x8C', '\n', '\b', '\f', '\b', '\xE', '\b', '\x8F', '\v', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\a', '\t', '\x97', '\n', '\t', '\f', '\t', '\xE', '\t', '\x9A', 
		'\v', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x5', '\n', '\xA7', '\n', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\a', '\v', '\xB3', '\n', '\v', '\f', 
		'\v', '\xE', '\v', '\xB6', '\v', '\v', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', '\xBE', '\n', 
		'\f', '\f', '\f', '\xE', '\f', '\xC1', '\v', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\a', '\r', '\xCD', '\n', '\r', 
		'\f', '\r', '\xE', '\r', '\xD0', '\v', '\r', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', '\xDC', '\n', '\xE', 
		'\f', '\xE', '\xE', '\xE', '\xDF', '\v', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\a', '\x10', '\xEA', '\n', '\x10', '\f', 
		'\x10', '\xE', '\x10', '\xED', '\v', '\x10', '\x5', '\x10', '\xEF', '\n', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '\x1AC', '\n', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x2', '\x2', '\x14', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', 
		'\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', 
		'\x2', '\x2', '\x2', '\x1E0', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '\x33', '\x3', '\x2', '\x2', '\x2', '\x6', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\b', 'U', '\x3', '\x2', '\x2', '\x2', '\n', 'W', '\x3', 
		'\x2', '\x2', '\x2', '\f', '\x66', '\x3', '\x2', '\x2', '\x2', '\xE', 
		'u', '\x3', '\x2', '\x2', '\x2', '\x10', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x12', '\xA6', '\x3', '\x2', '\x2', '\x2', '\x14', '\xA8', '\x3', 
		'\x2', '\x2', '\x2', '\x16', '\xB7', '\x3', '\x2', '\x2', '\x2', '\x18', 
		'\xC2', '\x3', '\x2', '\x2', '\x2', '\x1A', '\xD1', '\x3', '\x2', '\x2', 
		'\x2', '\x1C', '\xE0', '\x3', '\x2', '\x2', '\x2', '\x1E', '\xEE', '\x3', 
		'\x2', '\x2', '\x2', ' ', '\xF0', '\x3', '\x2', '\x2', '\x2', '\"', '\x1AB', 
		'\x3', '\x2', '\x2', '\x2', '$', '\x1AD', '\x3', '\x2', '\x2', '\x2', 
		'&', '\'', '\x5', '\"', '\x12', '\x2', '\'', '(', '\a', '\x3', '\x2', 
		'\x2', '(', ')', '\b', '\x2', '\x1', '\x2', ')', '.', '\x3', '\x2', '\x2', 
		'\x2', '*', '+', '\x5', '\"', '\x12', '\x2', '+', ',', '\b', '\x2', '\x1', 
		'\x2', ',', '.', '\x3', '\x2', '\x2', '\x2', '-', '&', '\x3', '\x2', '\x2', 
		'\x2', '-', '*', '\x3', '\x2', '\x2', '\x2', '.', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x30', '\a', '\x4', '\x2', '\x2', '\x30', '\x31', 
		'\x5', '\x2', '\x2', '\x2', '\x31', '\x32', '\b', '\x3', '\x1', '\x2', 
		'\x32', '\x34', '\x3', '\x2', '\x2', '\x2', '\x33', '/', '\x3', '\x2', 
		'\x2', '\x2', '\x34', '\x35', '\x3', '\x2', '\x2', '\x2', '\x35', '\x33', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\x3', '\x2', '\x2', '\x2', 
		'\x36', '\x5', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\x5', '\x2', 
		'\x2', '\x2', '\x38', '<', '\b', '\x4', '\x1', '\x2', '\x39', ':', '\x5', 
		'\x4', '\x3', '\x2', ':', ';', '\b', '\x4', '\x1', '\x2', ';', '=', '\x3', 
		'\x2', '\x2', '\x2', '<', '\x39', '\x3', '\x2', '\x2', '\x2', '<', '=', 
		'\x3', '\x2', '\x2', '\x2', '=', '\a', '\x3', '\x2', '\x2', '\x2', '>', 
		'?', '\a', '\x5', '\x2', '\x2', '?', '@', '\x5', '\x6', '\x4', '\x2', 
		'@', '\x41', '\b', '\x5', '\x1', '\x2', '\x41', 'G', '\x3', '\x2', '\x2', 
		'\x2', '\x42', '\x43', '\a', '\x6', '\x2', '\x2', '\x43', '\x44', '\x5', 
		'\x6', '\x4', '\x2', '\x44', '\x45', '\b', '\x5', '\x1', '\x2', '\x45', 
		'G', '\x3', '\x2', '\x2', '\x2', '\x46', '>', '\x3', '\x2', '\x2', '\x2', 
		'\x46', '\x42', '\x3', '\x2', '\x2', '\x2', 'G', 'V', '\x3', '\x2', '\x2', 
		'\x2', 'H', 'I', '\a', '\x5', '\x2', '\x2', 'I', 'J', '\x5', '\b', '\x5', 
		'\x2', 'J', 'K', '\b', '\x5', '\x1', '\x2', 'K', 'Q', '\x3', '\x2', '\x2', 
		'\x2', 'L', 'M', '\a', '\x6', '\x2', '\x2', 'M', 'N', '\x5', '\b', '\x5', 
		'\x2', 'N', 'O', '\b', '\x5', '\x1', '\x2', 'O', 'Q', '\x3', '\x2', '\x2', 
		'\x2', 'P', 'H', '\x3', '\x2', '\x2', '\x2', 'P', 'L', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'V', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x5', '\x6', '\x4', 
		'\x2', 'S', 'T', '\b', '\x5', '\x1', '\x2', 'T', 'V', '\x3', '\x2', '\x2', 
		'\x2', 'U', '\x46', '\x3', '\x2', '\x2', '\x2', 'U', 'P', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'R', '\x3', '\x2', '\x2', '\x2', 'V', '\t', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'X', '\x5', '\b', '\x5', '\x2', 'X', '\x63', 
		'\b', '\x6', '\x1', '\x2', 'Y', 'Z', '\a', '\a', '\x2', '\x2', 'Z', '[', 
		'\x5', '\b', '\x5', '\x2', '[', '\\', '\b', '\x6', '\x1', '\x2', '\\', 
		'\x62', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '\b', '\x2', '\x2', 
		'^', '_', '\x5', '\b', '\x5', '\x2', '_', '`', '\b', '\x6', '\x1', '\x2', 
		'`', '\x62', '\x3', '\x2', '\x2', '\x2', '\x61', 'Y', '\x3', '\x2', '\x2', 
		'\x2', '\x61', ']', '\x3', '\x2', '\x2', '\x2', '\x62', '\x65', '\x3', 
		'\x2', '\x2', '\x2', '\x63', '\x61', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x64', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x65', '\x63', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\x5', 
		'\n', '\x6', '\x2', 'g', 'r', '\b', '\a', '\x1', '\x2', 'h', 'i', '\a', 
		'\x6', '\x2', '\x2', 'i', 'j', '\x5', '\n', '\x6', '\x2', 'j', 'k', '\b', 
		'\a', '\x1', '\x2', 'k', 'q', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', 
		'\x5', '\x2', '\x2', 'm', 'n', '\x5', '\n', '\x6', '\x2', 'n', 'o', '\b', 
		'\a', '\x1', '\x2', 'o', 'q', '\x3', '\x2', '\x2', '\x2', 'p', 'h', '\x3', 
		'\x2', '\x2', '\x2', 'p', 'l', '\x3', '\x2', '\x2', '\x2', 'q', 't', '\x3', 
		'\x2', '\x2', '\x2', 'r', 'p', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x3', 
		'\x2', '\x2', '\x2', 's', '\r', '\x3', '\x2', '\x2', '\x2', 't', 'r', 
		'\x3', '\x2', '\x2', '\x2', 'u', 'v', '\x5', '\f', '\a', '\x2', 'v', '\x8D', 
		'\b', '\b', '\x1', '\x2', 'w', 'x', '\a', '\t', '\x2', '\x2', 'x', 'y', 
		'\x5', '\f', '\a', '\x2', 'y', 'z', '\b', '\b', '\x1', '\x2', 'z', '\x8C', 
		'\x3', '\x2', '\x2', '\x2', '{', '|', '\a', '\n', '\x2', '\x2', '|', '}', 
		'\x5', '\f', '\a', '\x2', '}', '~', '\b', '\b', '\x1', '\x2', '~', '\x8C', 
		'\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\a', '\v', '\x2', '\x2', 
		'\x80', '\x81', '\x5', '\f', '\a', '\x2', '\x81', '\x82', '\b', '\b', 
		'\x1', '\x2', '\x82', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', 
		'\a', '\f', '\x2', '\x2', '\x84', '\x85', '\x5', '\f', '\a', '\x2', '\x85', 
		'\x86', '\b', '\b', '\x1', '\x2', '\x86', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x87', '\x88', '\a', '\r', '\x2', '\x2', '\x88', '\x89', '\x5', 
		'\f', '\a', '\x2', '\x89', '\x8A', '\b', '\b', '\x1', '\x2', '\x8A', '\x8C', 
		'\x3', '\x2', '\x2', '\x2', '\x8B', 'w', '\x3', '\x2', '\x2', '\x2', '\x8B', 
		'{', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x83', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\xF', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x91', '\x5', '\xE', '\b', '\x2', '\x91', 
		'\x98', '\b', '\t', '\x1', '\x2', '\x92', '\x93', '\a', '\xE', '\x2', 
		'\x2', '\x93', '\x94', '\x5', '\xE', '\b', '\x2', '\x94', '\x95', '\b', 
		'\t', '\x1', '\x2', '\x95', '\x97', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x97', '\x9A', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x96', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\x11', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\a', '\xF', '\x2', 
		'\x2', '\x9C', '\x9D', '\x5', '\x10', '\t', '\x2', '\x9D', '\x9E', '\b', 
		'\n', '\x1', '\x2', '\x9E', '\xA7', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\xA0', '\a', '\xF', '\x2', '\x2', '\xA0', '\xA1', '\x5', '\x12', '\n', 
		'\x2', '\xA1', '\xA2', '\b', '\n', '\x1', '\x2', '\xA2', '\xA7', '\x3', 
		'\x2', '\x2', '\x2', '\xA3', '\xA4', '\x5', '\x10', '\t', '\x2', '\xA4', 
		'\xA5', '\b', '\n', '\x1', '\x2', '\xA5', '\xA7', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\x9B', '\x3', '\x2', '\x2', '\x2', '\xA6', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA7', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x5', '\x12', '\n', 
		'\x2', '\xA9', '\xB4', '\b', '\v', '\x1', '\x2', '\xAA', '\xAB', '\a', 
		'\x10', '\x2', '\x2', '\xAB', '\xAC', '\x5', '\x12', '\n', '\x2', '\xAC', 
		'\xAD', '\b', '\v', '\x1', '\x2', '\xAD', '\xB3', '\x3', '\x2', '\x2', 
		'\x2', '\xAE', '\xAF', '\a', '\x11', '\x2', '\x2', '\xAF', '\xB0', '\x5', 
		'\x12', '\n', '\x2', '\xB0', '\xB1', '\b', '\v', '\x1', '\x2', '\xB1', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB6', '\x3', 
		'\x2', '\x2', '\x2', '\xB4', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\xB5', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB8', '\x5', 
		'\x14', '\v', '\x2', '\xB8', '\xBF', '\b', '\f', '\x1', '\x2', '\xB9', 
		'\xBA', '\a', '\x12', '\x2', '\x2', '\xBA', '\xBB', '\x5', '\x14', '\v', 
		'\x2', '\xBB', '\xBC', '\b', '\f', '\x1', '\x2', '\xBC', '\xBE', '\x3', 
		'\x2', '\x2', '\x2', '\xBD', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\xC1', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '\xBF', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC0', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\xC1', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xC2', 
		'\xC3', '\x5', '\x16', '\f', '\x2', '\xC3', '\xCE', '\b', '\r', '\x1', 
		'\x2', '\xC4', '\xC5', '\a', '\x13', '\x2', '\x2', '\xC5', '\xC6', '\x5', 
		'\x16', '\f', '\x2', '\xC6', '\xC7', '\b', '\r', '\x1', '\x2', '\xC7', 
		'\xCD', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC9', '\a', '\x14', '\x2', 
		'\x2', '\xC9', '\xCA', '\x5', '\x16', '\f', '\x2', '\xCA', '\xCB', '\b', 
		'\r', '\x1', '\x2', '\xCB', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCC', 
		'\xC4', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xC8', '\x3', '\x2', '\x2', 
		'\x2', '\xCD', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCC', '\x3', 
		'\x2', '\x2', '\x2', '\xCE', '\xCF', '\x3', '\x2', '\x2', '\x2', '\xCF', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xCE', '\x3', '\x2', '\x2', 
		'\x2', '\xD1', '\xD2', '\x5', '\x18', '\r', '\x2', '\xD2', '\xDD', '\b', 
		'\xE', '\x1', '\x2', '\xD3', '\xD4', '\a', '\x15', '\x2', '\x2', '\xD4', 
		'\xD5', '\x5', '\x18', '\r', '\x2', '\xD5', '\xD6', '\b', '\xE', '\x1', 
		'\x2', '\xD6', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\a', 
		'\x16', '\x2', '\x2', '\xD8', '\xD9', '\x5', '\x18', '\r', '\x2', '\xD9', 
		'\xDA', '\b', '\xE', '\x1', '\x2', '\xDA', '\xDC', '\x3', '\x2', '\x2', 
		'\x2', '\xDB', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xD7', '\x3', 
		'\x2', '\x2', '\x2', '\xDC', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xDD', 
		'\xDB', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDE', '\x3', '\x2', '\x2', 
		'\x2', '\xDE', '\x1B', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xDD', '\x3', 
		'\x2', '\x2', '\x2', '\xE0', '\xE1', '\x5', '\x1A', '\xE', '\x2', '\xE1', 
		'\xE2', '\b', '\xF', '\x1', '\x2', '\xE2', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\xE3', '\xE4', '\x5', '\x1C', '\xF', '\x2', '\xE4', '\xEB', '\b', 
		'\x10', '\x1', '\x2', '\xE5', '\xE6', '\a', '\x17', '\x2', '\x2', '\xE6', 
		'\xE7', '\x5', '\x1C', '\xF', '\x2', '\xE7', '\xE8', '\b', '\x10', '\x1', 
		'\x2', '\xE8', '\xEA', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xE5', '\x3', 
		'\x2', '\x2', '\x2', '\xEA', '\xED', '\x3', '\x2', '\x2', '\x2', '\xEB', 
		'\xE9', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xEC', '\x3', '\x2', '\x2', 
		'\x2', '\xEC', '\xEF', '\x3', '\x2', '\x2', '\x2', '\xED', '\xEB', '\x3', 
		'\x2', '\x2', '\x2', '\xEE', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xEE', 
		'\xEF', '\x3', '\x2', '\x2', '\x2', '\xEF', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\xF0', '\xF1', '\x5', '\x1C', '\xF', '\x2', '\xF1', '\xF2', '\b', 
		'\x11', '\x1', '\x2', '\xF2', '\xF3', '\a', '\x18', '\x2', '\x2', '\xF3', 
		'\xF4', '\x5', '\x1C', '\xF', '\x2', '\xF4', '\xF5', '\b', '\x11', '\x1', 
		'\x2', '\xF5', '!', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xF7', '\a', 
		'>', '\x2', '\x2', '\xF7', '\x1AC', '\b', '\x12', '\x1', '\x2', '\xF8', 
		'\xF9', '\a', '?', '\x2', '\x2', '\xF9', '\x1AC', '\b', '\x12', '\x1', 
		'\x2', '\xFA', '\xFB', '\a', '@', '\x2', '\x2', '\xFB', '\x1AC', '\b', 
		'\x12', '\x1', '\x2', '\xFC', '\xFD', '\a', '\x19', '\x2', '\x2', '\xFD', 
		'\xFE', '\x5', '\x1C', '\xF', '\x2', '\xFE', '\xFF', '\a', '\x1A', '\x2', 
		'\x2', '\xFF', '\x100', '\b', '\x12', '\x1', '\x2', '\x100', '\x1AC', 
		'\x3', '\x2', '\x2', '\x2', '\x101', '\x102', '\a', '\x1B', '\x2', '\x2', 
		'\x102', '\x103', '\x5', ' ', '\x11', '\x2', '\x103', '\x104', '\a', '\x1C', 
		'\x2', '\x2', '\x104', '\x105', '\b', '\x12', '\x1', '\x2', '\x105', '\x1AC', 
		'\x3', '\x2', '\x2', '\x2', '\x106', '\x107', '\a', '\x1D', '\x2', '\x2', 
		'\x107', '\x108', '\x5', ' ', '\x11', '\x2', '\x108', '\x109', '\a', '\x1C', 
		'\x2', '\x2', '\x109', '\x10A', '\b', '\x12', '\x1', '\x2', '\x10A', '\x1AC', 
		'\x3', '\x2', '\x2', '\x2', '\x10B', '\x10C', '\a', '\x1D', '\x2', '\x2', 
		'\x10C', '\x10D', '\x5', ' ', '\x11', '\x2', '\x10D', '\x10E', '\a', '\x1E', 
		'\x2', '\x2', '\x10E', '\x10F', '\b', '\x12', '\x1', '\x2', '\x10F', '\x1AC', 
		'\x3', '\x2', '\x2', '\x2', '\x110', '\x111', '\a', '\x1D', '\x2', '\x2', 
		'\x111', '\x112', '\x5', ' ', '\x11', '\x2', '\x112', '\x113', '\a', '\x1E', 
		'\x2', '\x2', '\x113', '\x114', '\b', '\x12', '\x1', '\x2', '\x114', '\x1AC', 
		'\x3', '\x2', '\x2', '\x2', '\x115', '\x116', '\a', '\x1B', '\x2', '\x2', 
		'\x116', '\x117', '\x5', '\x1C', '\xF', '\x2', '\x117', '\x118', '\a', 
		'\x1C', '\x2', '\x2', '\x118', '\x119', '\b', '\x12', '\x1', '\x2', '\x119', 
		'\x1AC', '\x3', '\x2', '\x2', '\x2', '\x11A', '\x11B', '\a', '\x1F', '\x2', 
		'\x2', '\x11B', '\x11C', '\x5', '\x1E', '\x10', '\x2', '\x11C', '\x11D', 
		'\a', ' ', '\x2', '\x2', '\x11D', '\x11E', '\b', '\x12', '\x1', '\x2', 
		'\x11E', '\x1AC', '\x3', '\x2', '\x2', '\x2', '\x11F', '\x120', '\a', 
		'!', '\x2', '\x2', '\x120', '\x121', '\x5', '\x1E', '\x10', '\x2', '\x121', 
		'\x122', '\a', '\x1C', '\x2', '\x2', '\x122', '\x123', '\b', '\x12', '\x1', 
		'\x2', '\x123', '\x1AC', '\x3', '\x2', '\x2', '\x2', '\x124', '\x125', 
		'\a', '\"', '\x2', '\x2', '\x125', '\x126', '\x5', '\x1E', '\x10', '\x2', 
		'\x126', '\x127', '\a', '\x1C', '\x2', '\x2', '\x127', '\x128', '\b', 
		'\x12', '\x1', '\x2', '\x128', '\x1AC', '\x3', '\x2', '\x2', '\x2', '\x129', 
		'\x12A', '\a', '#', '\x2', '\x2', '\x12A', '\x12B', '\x5', '\x1E', '\x10', 
		'\x2', '\x12B', '\x12C', '\a', '\x1C', '\x2', '\x2', '\x12C', '\x12D', 
		'\b', '\x12', '\x1', '\x2', '\x12D', '\x1AC', '\x3', '\x2', '\x2', '\x2', 
		'\x12E', '\x12F', '\a', '$', '\x2', '\x2', '\x12F', '\x130', '\x5', '\x1E', 
		'\x10', '\x2', '\x130', '\x131', '\a', '\x1C', '\x2', '\x2', '\x131', 
		'\x132', '\b', '\x12', '\x1', '\x2', '\x132', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x133', '\x134', '\a', '%', '\x2', '\x2', '\x134', '\x135', '\x5', 
		'\x1E', '\x10', '\x2', '\x135', '\x136', '\a', '\x1C', '\x2', '\x2', '\x136', 
		'\x137', '\b', '\x12', '\x1', '\x2', '\x137', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x138', '\x139', '\a', '&', '\x2', '\x2', '\x139', '\x13A', '\x5', 
		'\x1E', '\x10', '\x2', '\x13A', '\x13B', '\a', '\x1C', '\x2', '\x2', '\x13B', 
		'\x13C', '\b', '\x12', '\x1', '\x2', '\x13C', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x13D', '\x13E', '\a', '\'', '\x2', '\x2', '\x13E', '\x13F', '\x5', 
		'\x1E', '\x10', '\x2', '\x13F', '\x140', '\a', '\x1C', '\x2', '\x2', '\x140', 
		'\x141', '\b', '\x12', '\x1', '\x2', '\x141', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x142', '\x143', '\a', '(', '\x2', '\x2', '\x143', '\x144', '\x5', 
		'\x1E', '\x10', '\x2', '\x144', '\x145', '\a', '\x1C', '\x2', '\x2', '\x145', 
		'\x146', '\b', '\x12', '\x1', '\x2', '\x146', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x147', '\x148', '\a', ')', '\x2', '\x2', '\x148', '\x149', '\x5', 
		'\x1E', '\x10', '\x2', '\x149', '\x14A', '\a', '\x1C', '\x2', '\x2', '\x14A', 
		'\x14B', '\b', '\x12', '\x1', '\x2', '\x14B', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x14C', '\x14D', '\a', '*', '\x2', '\x2', '\x14D', '\x14E', '\x5', 
		'\x1E', '\x10', '\x2', '\x14E', '\x14F', '\a', '\x1C', '\x2', '\x2', '\x14F', 
		'\x150', '\b', '\x12', '\x1', '\x2', '\x150', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x151', '\x152', '\a', '+', '\x2', '\x2', '\x152', '\x153', '\x5', 
		'\x1E', '\x10', '\x2', '\x153', '\x154', '\a', '\x1C', '\x2', '\x2', '\x154', 
		'\x155', '\b', '\x12', '\x1', '\x2', '\x155', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x156', '\x157', '\a', ',', '\x2', '\x2', '\x157', '\x158', '\x5', 
		'\x1E', '\x10', '\x2', '\x158', '\x159', '\a', '\x1C', '\x2', '\x2', '\x159', 
		'\x15A', '\b', '\x12', '\x1', '\x2', '\x15A', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x15B', '\x15C', '\a', '-', '\x2', '\x2', '\x15C', '\x15D', '\x5', 
		'\x1E', '\x10', '\x2', '\x15D', '\x15E', '\a', '\x1C', '\x2', '\x2', '\x15E', 
		'\x15F', '\b', '\x12', '\x1', '\x2', '\x15F', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x160', '\x161', '\a', '.', '\x2', '\x2', '\x161', '\x162', '\x5', 
		'\x1E', '\x10', '\x2', '\x162', '\x163', '\a', '\x1C', '\x2', '\x2', '\x163', 
		'\x164', '\b', '\x12', '\x1', '\x2', '\x164', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x165', '\x166', '\a', '/', '\x2', '\x2', '\x166', '\x167', '\x5', 
		'\x1E', '\x10', '\x2', '\x167', '\x168', '\a', '\x1C', '\x2', '\x2', '\x168', 
		'\x169', '\b', '\x12', '\x1', '\x2', '\x169', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x16A', '\x16B', '\a', '\x30', '\x2', '\x2', '\x16B', '\x16C', 
		'\x5', '\x1E', '\x10', '\x2', '\x16C', '\x16D', '\a', '\x1C', '\x2', '\x2', 
		'\x16D', '\x16E', '\b', '\x12', '\x1', '\x2', '\x16E', '\x1AC', '\x3', 
		'\x2', '\x2', '\x2', '\x16F', '\x170', '\a', '\x31', '\x2', '\x2', '\x170', 
		'\x171', '\x5', '\x1E', '\x10', '\x2', '\x171', '\x172', '\a', '\x1C', 
		'\x2', '\x2', '\x172', '\x173', '\b', '\x12', '\x1', '\x2', '\x173', '\x1AC', 
		'\x3', '\x2', '\x2', '\x2', '\x174', '\x175', '\a', '\x32', '\x2', '\x2', 
		'\x175', '\x176', '\x5', '\x1E', '\x10', '\x2', '\x176', '\x177', '\a', 
		'\x1C', '\x2', '\x2', '\x177', '\x178', '\b', '\x12', '\x1', '\x2', '\x178', 
		'\x1AC', '\x3', '\x2', '\x2', '\x2', '\x179', '\x17A', '\a', '\x33', '\x2', 
		'\x2', '\x17A', '\x17B', '\x5', '\x1E', '\x10', '\x2', '\x17B', '\x17C', 
		'\a', '\x1C', '\x2', '\x2', '\x17C', '\x17D', '\b', '\x12', '\x1', '\x2', 
		'\x17D', '\x1AC', '\x3', '\x2', '\x2', '\x2', '\x17E', '\x17F', '\a', 
		'\x34', '\x2', '\x2', '\x17F', '\x180', '\x5', '\x1E', '\x10', '\x2', 
		'\x180', '\x181', '\a', '\x1C', '\x2', '\x2', '\x181', '\x182', '\b', 
		'\x12', '\x1', '\x2', '\x182', '\x1AC', '\x3', '\x2', '\x2', '\x2', '\x183', 
		'\x184', '\a', '\x35', '\x2', '\x2', '\x184', '\x185', '\x5', '\x1E', 
		'\x10', '\x2', '\x185', '\x186', '\a', '\x1C', '\x2', '\x2', '\x186', 
		'\x187', '\b', '\x12', '\x1', '\x2', '\x187', '\x1AC', '\x3', '\x2', '\x2', 
		'\x2', '\x188', '\x189', '\a', '\x36', '\x2', '\x2', '\x189', '\x18A', 
		'\x5', '\x1E', '\x10', '\x2', '\x18A', '\x18B', '\a', '\x1C', '\x2', '\x2', 
		'\x18B', '\x18C', '\b', '\x12', '\x1', '\x2', '\x18C', '\x1AC', '\x3', 
		'\x2', '\x2', '\x2', '\x18D', '\x18E', '\a', '\x37', '\x2', '\x2', '\x18E', 
		'\x18F', '\x5', '\x1E', '\x10', '\x2', '\x18F', '\x190', '\a', '\x1C', 
		'\x2', '\x2', '\x190', '\x191', '\b', '\x12', '\x1', '\x2', '\x191', '\x1AC', 
		'\x3', '\x2', '\x2', '\x2', '\x192', '\x193', '\a', '\x38', '\x2', '\x2', 
		'\x193', '\x194', '\x5', '\x1E', '\x10', '\x2', '\x194', '\x195', '\a', 
		'\x1C', '\x2', '\x2', '\x195', '\x196', '\b', '\x12', '\x1', '\x2', '\x196', 
		'\x1AC', '\x3', '\x2', '\x2', '\x2', '\x197', '\x198', '\a', '\x39', '\x2', 
		'\x2', '\x198', '\x199', '\x5', '\x1E', '\x10', '\x2', '\x199', '\x19A', 
		'\a', '\x1C', '\x2', '\x2', '\x19A', '\x19B', '\b', '\x12', '\x1', '\x2', 
		'\x19B', '\x1AC', '\x3', '\x2', '\x2', '\x2', '\x19C', '\x19D', '\a', 
		':', '\x2', '\x2', '\x19D', '\x19E', '\x5', '\x1E', '\x10', '\x2', '\x19E', 
		'\x19F', '\a', '\x1C', '\x2', '\x2', '\x19F', '\x1A0', '\b', '\x12', '\x1', 
		'\x2', '\x1A0', '\x1AC', '\x3', '\x2', '\x2', '\x2', '\x1A1', '\x1A2', 
		'\a', ';', '\x2', '\x2', '\x1A2', '\x1A3', '\x5', '\x1E', '\x10', '\x2', 
		'\x1A3', '\x1A4', '\a', '\x1C', '\x2', '\x2', '\x1A4', '\x1A5', '\b', 
		'\x12', '\x1', '\x2', '\x1A5', '\x1AC', '\x3', '\x2', '\x2', '\x2', '\x1A6', 
		'\x1A7', '\a', '<', '\x2', '\x2', '\x1A7', '\x1A8', '\x5', '\x1E', '\x10', 
		'\x2', '\x1A8', '\x1A9', '\a', '\x1C', '\x2', '\x2', '\x1A9', '\x1AA', 
		'\b', '\x12', '\x1', '\x2', '\x1AA', '\x1AC', '\x3', '\x2', '\x2', '\x2', 
		'\x1AB', '\xF6', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\xF8', '\x3', '\x2', 
		'\x2', '\x2', '\x1AB', '\xFA', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\xFC', 
		'\x3', '\x2', '\x2', '\x2', '\x1AB', '\x101', '\x3', '\x2', '\x2', '\x2', 
		'\x1AB', '\x106', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x10B', '\x3', 
		'\x2', '\x2', '\x2', '\x1AB', '\x110', '\x3', '\x2', '\x2', '\x2', '\x1AB', 
		'\x115', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x11A', '\x3', '\x2', '\x2', 
		'\x2', '\x1AB', '\x11F', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x124', 
		'\x3', '\x2', '\x2', '\x2', '\x1AB', '\x129', '\x3', '\x2', '\x2', '\x2', 
		'\x1AB', '\x12E', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x133', '\x3', 
		'\x2', '\x2', '\x2', '\x1AB', '\x138', '\x3', '\x2', '\x2', '\x2', '\x1AB', 
		'\x13D', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x142', '\x3', '\x2', '\x2', 
		'\x2', '\x1AB', '\x147', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x14C', 
		'\x3', '\x2', '\x2', '\x2', '\x1AB', '\x151', '\x3', '\x2', '\x2', '\x2', 
		'\x1AB', '\x156', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x15B', '\x3', 
		'\x2', '\x2', '\x2', '\x1AB', '\x160', '\x3', '\x2', '\x2', '\x2', '\x1AB', 
		'\x165', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x16A', '\x3', '\x2', '\x2', 
		'\x2', '\x1AB', '\x16F', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x174', 
		'\x3', '\x2', '\x2', '\x2', '\x1AB', '\x179', '\x3', '\x2', '\x2', '\x2', 
		'\x1AB', '\x17E', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x183', '\x3', 
		'\x2', '\x2', '\x2', '\x1AB', '\x188', '\x3', '\x2', '\x2', '\x2', '\x1AB', 
		'\x18D', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x192', '\x3', '\x2', '\x2', 
		'\x2', '\x1AB', '\x197', '\x3', '\x2', '\x2', '\x2', '\x1AB', '\x19C', 
		'\x3', '\x2', '\x2', '\x2', '\x1AB', '\x1A1', '\x3', '\x2', '\x2', '\x2', 
		'\x1AB', '\x1A6', '\x3', '\x2', '\x2', '\x2', '\x1AC', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x1AD', '\x1AE', '\x5', '\x1C', '\xF', '\x2', '\x1AE', 
		'\x1AF', '\a', '\x2', '\x2', '\x3', '\x1AF', '\x1B0', '\b', '\x13', '\x1', 
		'\x2', '\x1B0', '%', '\x3', '\x2', '\x2', '\x2', '\x1A', '-', '\x35', 
		'<', '\x46', 'P', 'U', '\x61', '\x63', 'p', 'r', '\x8B', '\x8D', '\x98', 
		'\xA6', '\xB2', '\xB4', '\xBF', '\xCC', '\xCE', '\xDB', '\xDD', '\xEB', 
		'\xEE', '\x1AB',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace AngouriMath.Core.Antlr
