//
// Copyright (c) 2019-2026 Angouri.
// AngouriMath is licensed under MIT.
// Details: https://github.com/asc-community/AngouriMath/blob/master/LICENSE.md.
// Website: https://am.angouri.org.
//

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AngouriMath.Generators
{
    /// <summary>
    /// Turns each arm of a rewrite rule <c>switch</c> into an addressable value, without the
    /// <c>switch</c> ceasing to be the thing a human edits.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is what https://github.com/asc-community/AngouriMath/issues/825 settled on. The two
    /// alternatives both fail on something measured: transcribing forty arms by hand is forty
    /// chances to change a pattern silently, and expressing them through the runtime matcher costs
    /// about five percent of <c>Simplify</c> per rule set exchanged. A generator over the arms
    /// costs nothing at run time, because the method it reads is left exactly as it was and keeps
    /// being what the simplifier calls.
    /// </para>
    /// <para>
    /// The arm is copied as syntax rather than re-derived, so the generated rule cannot say
    /// something the arm does not. What is derived is only what a reader would otherwise have to
    /// count for themselves: the node type at the root of the pattern, and whether the rewrite
    /// grows, shrinks or rearranges.
    /// </para>
    /// </remarks>
    [Generator(LanguageNames.CSharp)]
    public sealed class RuleRegistryGenerator : IIncrementalGenerator
    {
        private const string AttributeName = "AddressableRules";

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var files = context.SyntaxProvider.CreateSyntaxProvider(
                    predicate: static (node, _) => IsCandidate(node),
                    transform: static (ctx, _) => Describe((MethodDeclarationSyntax)ctx.Node))
                .Where(static file => file is not null);

            // The transform produces the finished text, so what travels through the pipeline is a
            // pair of strings. Anything holding a syntax node or a symbol would keep a compilation
            // alive and compare unequal on every keystroke.
            context.RegisterSourceOutput(files, static (spc, file) =>
                spc.AddSource(file!.HintName, SourceText.From(file.Source, Encoding.UTF8)));
        }

        private static bool IsCandidate(SyntaxNode node)
            => node is MethodDeclarationSyntax method
               && method.AttributeLists
                   .SelectMany(list => list.Attributes)
                   .Any(attribute => NameOf(attribute) is AttributeName or AttributeName + "Attribute");

        private static string NameOf(AttributeSyntax attribute)
            => attribute.Name switch
            {
                QualifiedNameSyntax qualified => qualified.Right.Identifier.Text,
                SimpleNameSyntax simple => simple.Identifier.Text,
                _ => attribute.Name.ToString()
            };

        private sealed class GeneratedFile
        {
            internal GeneratedFile(string hintName, string source)
                => (HintName, Source) = (hintName, source);

            internal string HintName { get; }
            internal string Source { get; }
        }

        private static GeneratedFile? Describe(MethodDeclarationSyntax method)
        {
            var unit = method.FirstAncestorOrSelf<CompilationUnitSyntax>();
            var owner = method.FirstAncestorOrSelf<TypeDeclarationSyntax>();
            if (unit is null || owner is null)
                return null;

            var containers = new List<TypeDeclarationSyntax>();
            for (var at = owner; at is not null; at = at.Parent as TypeDeclarationSyntax)
                containers.Insert(0, at);

            var namespaceName = NamespaceOf(method);
            var hint = Sanitize(namespaceName + "." + string.Join(".", containers.Select(c => c.Identifier.Text))
                                + "." + method.Identifier.Text) + ".Rules.g.cs";

            var text = new StringBuilder();
            text.AppendLine("// <auto-generated/>");
            text.AppendLine("#nullable enable");
            // The arms are copied verbatim, so they need the names the file they came from had in
            // scope. Carrying its using directives over is what makes that true, and a directive
            // the compilation already has globally is then written twice.
            text.AppendLine("#pragma warning disable CS0105 // duplicate using directive");
            text.AppendLine("#pragma warning disable CS8933 // using directive appeared previously as global using");
            foreach (var directive in unit.Usings)
                text.AppendLine(directive.ToString());
            foreach (var declared in method.Ancestors().OfType<BaseNamespaceDeclarationSyntax>())
                foreach (var directive in declared.Usings)
                    text.AppendLine(directive.ToString());
            text.AppendLine();

            var indent = "";
            if (namespaceName.Length > 0)
            {
                text.AppendLine($"namespace {namespaceName}");
                text.AppendLine("{");
                indent = "    ";
            }
            foreach (var container in containers)
            {
                text.AppendLine($"{indent}{Modifiers(container)} partial {container.Keyword.Text} {container.Identifier.Text}");
                text.AppendLine($"{indent}{{");
                indent += "    ";
            }

            var body = Body(method, indent);
            if (body is null)
            {
                // A `#error` rather than a reported diagnostic: it cannot be turned off by a
                // severity setting, which matters because the failure mode being guarded against
                // is a rule set silently having no rules rather than a rule being wrong.
                text.AppendLine($"{indent}#error AddressableRules: '{method.Identifier.Text}' must be an "
                    + "expression-bodied method whose body is `x switch { ... }`, `x => x switch { ... }`, "
                    + "or `x is pattern [&& guard] ? replacement : x`.");
            }
            else
                text.Append(body);

            foreach (var _ in containers)
            {
                indent = indent.Substring(4);
                text.AppendLine($"{indent}}}");
            }
            if (namespaceName.Length > 0)
                text.AppendLine("}");

            return new GeneratedFile(hint, text.ToString());
        }

        private static string Modifiers(TypeDeclarationSyntax type)
            => string.Join(" ", type.Modifiers.Where(m => !m.IsKind(SyntaxKind.PartialKeyword)).Select(m => m.Text));

        private static string NamespaceOf(SyntaxNode node)
        {
            var names = node.Ancestors().OfType<BaseNamespaceDeclarationSyntax>()
                .Select(declared => declared.Name.ToString()).Reverse();
            return string.Join(".", names);
        }

        private static string Sanitize(string name)
        {
            var builder = new StringBuilder(name.Length);
            foreach (var c in name)
                builder.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '.');
            return builder.ToString();
        }

        private static string? Body(MethodDeclarationSyntax method, string indent)
        {
            // Three shapes are read. A rule set written directly as a switch over its expression,
            //     static Entity CommonRules(Entity x) => x switch { ... }
            // a *factory* for one, which is how a set parameterised by something that is not the
            // expression is written,
            //     static Func<Entity, Entity> SortRules(SortLevel level) => x => x switch { ... }
            // and a set that is a single rule, which needs no switch to say so,
            //     static Entity InvertNegativePowers(Entity x) => x is Powf(...) ? ... : x;
            // The arms of a factory close over its parameters, so they cannot be a static field;
            // they are emitted as a method taking the same parameters instead.
            var lambda = method.ExpressionBody?.Expression as SimpleLambdaExpressionSyntax;
            var inner = lambda?.Body as ExpressionSyntax ?? method.ExpressionBody?.Expression;
            // Which parameter is the expression being rewritten. A factory says so by being a
            // lambda; a switch says so by naming it; and a method with one parameter has only the
            // one to offer. A switch that takes a second parameter — a sort level, say — is read
            // by asking the switch rather than by counting, which is the whole of this.
            ParameterSyntax? parameter =
                lambda is not null ? lambda.Parameter
                : inner is SwitchExpressionSyntax { GoverningExpression: IdentifierNameSyntax named }
                    ? method.ParameterList.Parameters.FirstOrDefault(p => p.Identifier.Text == named.Identifier.Text)
                : method.ParameterList.Parameters.Count == 1 ? method.ParameterList.Parameters[0]
                : null;
            if (parameter is null)
                return null;
            var subject = parameter.Identifier.Text;
            // Everything else the method takes is closed over by the arms, so it decides whether
            // they can be a field at all.
            var captured = method.ParameterList.Parameters.Where(p => p != parameter).ToList();
            // A lambda parameter is written without its type, and the arms are copied into a
            // context where nothing infers it, so it is named rather than echoed.
            var parameterType = parameter.Type?.ToString() ?? "global::AngouriMath.Entity";

            var arms = ArmsOf(inner, subject, indent, method.GetLeadingTrivia());
            if (arms is null)
                return null;
            var names = new Dictionary<string, int>(StringComparer.Ordinal);

            var text = new StringBuilder();
            text.AppendLine($"{indent}/// <summary>");
            text.AppendLine($"{indent}/// The arms of <see cref=\"{method.Identifier.Text}\"/>, each one addressable on its own.");
            text.AppendLine($"{indent}/// Generated from the <c>switch</c> itself, so the two cannot disagree.");
            text.AppendLine($"{indent}/// </summary>");
            if (captured.Count == 0)
            {
                text.AppendLine($"{indent}[global::AngouriMath.Core.ConstantField]");
                text.AppendLine($"{indent}internal static readonly global::System.Collections.Generic.IReadOnlyList"
                    + $"<global::AngouriMath.Core.Transformations.RewriteRule> {method.Identifier.Text}Arms =");
            }
            else
                text.AppendLine($"{indent}internal static global::System.Collections.Generic.IReadOnlyList"
                    + $"<global::AngouriMath.Core.Transformations.RewriteRule> {method.Identifier.Text}Arms"
                    + $"({string.Join(", ", captured)}) =>");
            text.AppendLine($"{indent}    new global::AngouriMath.Core.Transformations.RewriteRule[]");
            text.AppendLine($"{indent}    {{");

            for (var index = 0; index < arms.Count; index++)
            {
                var arm = arms[index];
                var pattern = Flatten(arm.Pattern.ToString());
                var guard = arm.Guard is null ? null : Flatten(arm.Guard);
                var replacement = Flatten(arm.Replacement.ToString());
                var key = guard is null ? pattern : pattern + " when " + guard;
                names.TryGetValue(key, out var seen);
                names[key] = seen + 1;
                var name = seen == 0 ? key : $"{key} #{seen + 1}";

                var line = arm.Source.GetLocation().GetLineSpan().StartLinePosition.Line + 1;
                var nodeTypes = RootTypesOf(arm.Pattern);
                var growth = Growth(arm.Pattern, arm.Replacement);

                text.AppendLine($"{indent}        new global::AngouriMath.Core.Transformations.RewriteRule(");
                text.AppendLine($"{indent}            source: \"{method.Identifier.Text}\",");
                text.AppendLine($"{indent}            index: {index},");
                text.AppendLine($"{indent}            name: {Literal(name)},");
                text.AppendLine($"{indent}            description: {Literal(arm.Description)},");
                text.AppendLine($"{indent}            nodeTypes: new global::System.Type[] {{ "
                    + string.Join(", ", nodeTypes.Select(type => $"typeof({type})")) + " },");
                text.AppendLine($"{indent}            patternSource: {Literal(pattern)},");
                text.AppendLine($"{indent}            guardSource: {Literal(guard)},");
                text.AppendLine($"{indent}            replacementSource: {Literal(replacement)},");
                text.AppendLine($"{indent}            growth: global::AngouriMath.Core.Transformations.RewriteRuleGrowth.{growth},");
                text.AppendLine($"{indent}            sourceLine: {line},");
                // An arm that reads a captured parameter cannot be a static lambda.
                text.AppendLine($"{indent}            apply: {(captured.Count == 0 ? "static " : "")}global::AngouriMath.Entity? "
                    + $"({parameterType} {subject}) => {arm.Apply}),");
            }

            text.AppendLine($"{indent}    }};");
            return text.ToString();
        }

        /// <summary>One rule, whatever shape the method that holds it was written in.</summary>
        private sealed class Arm
        {
            internal Arm(PatternSyntax pattern, string? guard, ExpressionSyntax replacement,
                SyntaxNode source, string? description, string apply)
                => (Pattern, Guard, Replacement, Source, Description, Apply)
                    = (pattern, guard, replacement, source, description, apply);

            internal PatternSyntax Pattern { get; }
            internal string? Guard { get; }
            internal ExpressionSyntax Replacement { get; }
            /// <summary>What the rule was read from, for its line number.</summary>
            internal SyntaxNode Source { get; }
            internal string? Description { get; }
            /// <summary>The body of the generated <c>apply</c>, copied from the source it came from.</summary>
            internal string Apply { get; }
        }

        /// <summary>
        /// The rules a method body holds, or <see langword="null"/> where it is not a shape this
        /// can read. <paramref name="ownDoc"/> is the method's own leading trivia, which describes
        /// the rule when the method <i>is</i> one.
        /// </summary>
        private static List<Arm>? ArmsOf(ExpressionSyntax? body, string subject, string indent, SyntaxTriviaList ownDoc)
        {
            switch (body)
            {
                case SwitchExpressionSyntax dispatch
                    when dispatch.GoverningExpression is IdentifierNameSyntax governing
                         && governing.Identifier.Text == subject:
                    return dispatch.Arms
                        .Where(arm => arm.Pattern is not DiscardPatternSyntax)
                        .Select(arm => new Arm(
                            arm.Pattern,
                            arm.WhenClause?.Condition.ToString(),
                            arm.Expression,
                            arm,
                            Description(arm.GetLeadingTrivia()),
                            // A one-armed switch over the same subject, so the pattern binds its
                            // variables exactly as it does where it is written.
                            $"{subject} switch\n"
                            + $"{indent}            {{\n"
                            + $"{indent}                {arm.Pattern}"
                            + $"{(arm.WhenClause is null ? "" : " " + arm.WhenClause)} => {arm.Expression},\n"
                            + $"{indent}                _ => null\n"
                            + $"{indent}            }}"))
                        .ToList();

                // `subject is pattern [&& guard] ? replacement : subject` — a set that is a single
                // rule and needs no switch to say so. The false branch has to be the subject
                // itself; anything else is a second rewrite this would silently drop.
                case ConditionalExpressionSyntax conditional
                    when conditional.WhenFalse is IdentifierNameSyntax unchanged
                         && unchanged.Identifier.Text == subject:
                {
                    var conjuncts = Conjuncts(conditional.Condition);
                    if (conjuncts[0] is not IsPatternExpressionSyntax test
                        || test.Expression is not IdentifierNameSyntax tested
                        || tested.Identifier.Text != subject)
                        return null;
                    return new List<Arm>
                    {
                        new Arm(
                            test.Pattern,
                            conjuncts.Count == 1 ? null : string.Join(" && ", conjuncts.Skip(1)),
                            conditional.WhenTrue,
                            conditional,
                            Description(ownDoc),
                            // The condition is kept whole rather than rebuilt from the pattern and
                            // the guard: a later conjunct may declare what the replacement reads,
                            // which is how the polynomial rules are written.
                            $"{conditional.Condition} ? {conditional.WhenTrue} : null")
                    };
                }

                default:
                    return null;
            }
        }

        /// <summary>The value of one attribute of an XML tag, or null where it carries none.</summary>
        private static string? AttributeOf(string tag, string name)
        {
            var at = tag.IndexOf(name + "=\"", StringComparison.Ordinal);
            if (at < 0)
                return null;
            var from = at + name.Length + 2;
            var to = tag.IndexOf('"', from);
            return to < 0 ? null : tag.Substring(from, to - from);
        }

        /// <summary>The operands of a chain of <c>&amp;&amp;</c>, left to right.</summary>
        private static List<ExpressionSyntax> Conjuncts(ExpressionSyntax expression)
        {
            if (expression is not BinaryExpressionSyntax binary || !binary.IsKind(SyntaxKind.LogicalAndExpression))
                return new List<ExpressionSyntax> { expression };
            var operands = Conjuncts(binary.Left);
            operands.AddRange(Conjuncts(binary.Right));
            return operands;
        }

        /// <summary>The comment written above a rule, which is the rule stated as mathematics.</summary>
        private static string? Description(SyntaxTriviaList trivia)
        {
            // A `//` comment is prose and is taken as written: mathematics is full of `<` and `>`,
            // and reading it as XML would eat `a ^ (-1) => 1 / a` down to `a ^ (-1) 1 / a`. Only a
            // `///` comment is XML, and only there are the tags stripped.
            var lines = new List<string>();
            foreach (var item in trivia)
            {
                var line =
                    item.IsKind(SyntaxKind.SingleLineCommentTrivia) ? item.ToString().TrimStart('/').Trim()
                    : item.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) ? WithoutTags(item.ToString())
                    : "";
                if (line.Length > 0)
                    lines.Add(line);
            }
            return lines.Count == 0 ? null : string.Join(" ", lines);
        }

        /// <summary>
        /// A comment's text without its slashes or its XML, so that a <c>&lt;summary&gt;</c> above a
        /// single-rule method reads the same way a <c>//</c> above an arm does.
        /// </summary>
        private static string WithoutTags(string comment)
        {
            var text = new StringBuilder(comment.Length);
            for (var i = 0; i < comment.Length; i++)
            {
                if (comment[i] != '<')
                {
                    text.Append(comment[i]);
                    continue;
                }
                var end = comment.IndexOf('>', i);
                if (end < 0)
                    break;
                // A `see` carries its meaning in the attribute and has nothing between its tags, so
                // dropping it wholesale leaves a hole: "See  for what is and is not attempted".
                var cref = AttributeOf(comment.Substring(i + 1, end - i - 1), "cref");
                if (cref is not null)
                {
                    var head = cref.Substring(cref.IndexOf(':') + 1);
                    var arguments = head.IndexOf('(');
                    if (arguments >= 0)
                        head = head.Substring(0, arguments);
                    text.Append(head.Substring(head.LastIndexOf('.') + 1));
                }
                i = end;
            }
            return string.Join(" ", text.ToString()
                .Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(line => line.TrimStart().TrimStart('/').Trim())
                .Where(line => line.Length > 0));
        }

        /// <summary>
        /// The node types the pattern admits at its root. Usually one; two where the arm is an
        /// <c>or</c> of node types, and none where the constraint cannot be read off the syntax.
        /// </summary>
        /// <remarks>
        /// The list is a <i>necessary</i> condition and has to stay one, because the point of
        /// recording it is that a scheduler may skip the rule on any other type. So an
        /// unrecognised shape yields nothing rather than a guess, and an <c>and</c> takes one
        /// side's constraint — both hold, so either is necessary — while an <c>or</c> has to take
        /// both or neither.
        /// </remarks>
        private static IReadOnlyList<string> RootTypesOf(PatternSyntax pattern)
        {
            switch (pattern)
            {
                case RecursivePatternSyntax { Type: { } type }:
                    return new[] { type.ToString() };
                case DeclarationPatternSyntax declaration:
                    return new[] { declaration.Type.ToString() };
                case TypePatternSyntax typed:
                    return new[] { typed.Type.ToString() };
                case ParenthesizedPatternSyntax parenthesized:
                    return RootTypesOf(parenthesized.Pattern);
                case BinaryPatternSyntax binary when binary.IsKind(SyntaxKind.OrPattern):
                {
                    var left = RootTypesOf(binary.Left);
                    var right = RootTypesOf(binary.Right);
                    return left.Count == 0 || right.Count == 0
                        ? Array.Empty<string>()
                        : left.Concat(right).Distinct().ToArray();
                }
                case BinaryPatternSyntax binary when binary.IsKind(SyntaxKind.AndPattern):
                {
                    var left = RootTypesOf(binary.Left);
                    return left.Count > 0 ? left : RootTypesOf(binary.Right);
                }
                default:
                    return Array.Empty<string>();
            }
        }

        /// <summary>
        /// Whether the rewrite makes the expression bigger, smaller or the same size — counted as
        /// operators plus operands on each side.
        /// </summary>
        /// <remarks>
        /// A syntactic proxy, and deliberately a crude one: it counts what is written rather than
        /// what the expression evaluates to, so a rule whose replacement calls a helper is counted
        /// as the call. It says which way a rule moves and no more: two rules that both collect
        /// need not be related at all, so a saturation scheduler asking which rule undoes which
        /// gets no answer from this. That question needs a rule with two sides —
        /// <c>Docs/Contributing/ReversibleRules.md</c>.
        /// </remarks>
        private static string Growth(PatternSyntax pattern, ExpressionSyntax replacement)
        {
            var before = Size(pattern);
            var after = Size(replacement);
            return after > before ? "Expands" : after < before ? "Collects" : "Rearranges";
        }

        private static int Size(PatternSyntax pattern)
            => pattern switch
            {
                RecursivePatternSyntax recursive =>
                    1 + (recursive.PositionalPatternClause?.Subpatterns.Sum(sub => Size(sub.Pattern)) ?? 0)
                      + (recursive.PropertyPatternClause?.Subpatterns.Sum(sub => Size(sub.Pattern)) ?? 0),
                ParenthesizedPatternSyntax parenthesized => Size(parenthesized.Pattern),
                BinaryPatternSyntax binary => Size(binary.Left) + Size(binary.Right),
                UnaryPatternSyntax unary => Size(unary.Pattern),
                _ => 1
            };

        private static int Size(ExpressionSyntax expression)
            => expression switch
            {
                ParenthesizedExpressionSyntax parenthesized => Size(parenthesized.Expression),
                BinaryExpressionSyntax binary => 1 + Size(binary.Left) + Size(binary.Right),
                PrefixUnaryExpressionSyntax prefix => 1 + Size(prefix.Operand),
                CastExpressionSyntax cast => Size(cast.Expression),
                InvocationExpressionSyntax invocation =>
                    1 + invocation.ArgumentList.Arguments.Sum(argument => Size(argument.Expression))
                      + (invocation.Expression is MemberAccessExpressionSyntax access ? Size(access.Expression) : 0),
                ObjectCreationExpressionSyntax creation =>
                    1 + (creation.ArgumentList?.Arguments.Sum(argument => Size(argument.Expression)) ?? 0),
                MemberAccessExpressionSyntax access => 1 + Size(access.Expression),
                _ => 1
            };

        private static string Flatten(string text)
            => string.Join(" ", text.Split(new[] { '\r', '\n', '\t', ' ' }, StringSplitOptions.RemoveEmptyEntries));

        private static string Literal(string? text)
            => text is null ? "null" : "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
