//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Angourimath.g by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using System.Linq;
using System.Collections;
using AngouriMath;
using AngouriMath.Core;
using AngouriMath.Core.Numerix;
using System.Globalization;

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class AngourimathLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, NEWLINE=9, 
		ID=10, NUMBER=11, COMMENT=12, WS=13;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "NEWLINE", 
		"ID", "NUMBER", "COMMENT", "WS", "EXPONENT"
	};


	public AngourimathLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public AngourimathLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'^'", "'-'", "'+'", "'*'", "'/'", "'('", "')'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "NEWLINE", "ID", 
		"NUMBER", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Angourimath.g"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static AngourimathLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\xF', '\x8F', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x5', '\n', '\x31', 
		'\n', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x6', '\v', '\x36', 
		'\n', '\v', '\r', '\v', '\xE', '\v', '\x37', '\x3', '\v', '\x3', '\v', 
		'\x6', '\v', '<', '\n', '\v', '\r', '\v', '\xE', '\v', '=', '\x5', '\v', 
		'@', '\n', '\v', '\x3', '\f', '\x6', '\f', '\x43', '\n', '\f', '\r', '\f', 
		'\xE', '\f', '\x44', '\x3', '\f', '\x3', '\f', '\a', '\f', 'I', '\n', 
		'\f', '\f', '\f', '\xE', '\f', 'L', '\v', '\f', '\x3', '\f', '\x5', '\f', 
		'O', '\n', '\f', '\x3', '\f', '\x5', '\f', 'R', '\n', '\f', '\x3', '\f', 
		'\x5', '\f', 'U', '\n', '\f', '\x3', '\f', '\x6', '\f', 'X', '\n', '\f', 
		'\r', '\f', '\xE', '\f', 'Y', '\x3', '\f', '\x5', '\f', ']', '\n', '\f', 
		'\x3', '\f', '\x5', '\f', '`', '\n', '\f', '\x5', '\f', '\x62', '\n', 
		'\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\a', '\r', 
		'h', '\n', '\r', '\f', '\r', '\xE', '\r', 'k', '\v', '\r', '\x3', '\r', 
		'\x5', '\r', 'n', '\n', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\a', '\r', 'u', '\n', '\r', '\f', '\r', '\xE', '\r', 
		'x', '\v', '\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', '|', '\n', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x6', '\xE', '\x81', '\n', '\xE', 
		'\r', '\xE', '\xE', '\xE', '\x82', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x5', '\xF', '\x89', '\n', '\xF', '\x3', '\xF', 
		'\x6', '\xF', '\x8C', '\n', '\xF', '\r', '\xF', '\xE', '\xF', '\x8D', 
		'\x3', 'v', '\x2', '\x10', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', 
		'\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', 
		'\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x2', 
		'\x3', '\x2', '\b', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x5', '\x2', 
		'\x32', ';', '\x43', '\\', '\x63', '|', '\x4', '\x2', '\f', '\f', '\xF', 
		'\xF', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x4', '\x2', 'G', 'G', 'g', 
		'g', '\x4', '\x2', '-', '-', '/', '/', '\x2', '\xA1', '\x2', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'!', '\x3', '\x2', '\x2', '\x2', '\a', '#', '\x3', '\x2', '\x2', '\x2', 
		'\t', '%', '\x3', '\x2', '\x2', '\x2', '\v', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\r', ')', '\x3', '\x2', '\x2', '\x2', '\xF', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x11', '-', '\x3', '\x2', '\x2', '\x2', '\x13', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\x15', '\x35', '\x3', '\x2', '\x2', '\x2', 
		'\x17', '\x61', '\x3', '\x2', '\x2', '\x2', '\x19', '{', '\x3', '\x2', 
		'\x2', '\x2', '\x1B', '\x80', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x86', 
		'\x3', '\x2', '\x2', '\x2', '\x1F', ' ', '\a', '`', '\x2', '\x2', ' ', 
		'\x4', '\x3', '\x2', '\x2', '\x2', '!', '\"', '\a', '/', '\x2', '\x2', 
		'\"', '\x6', '\x3', '\x2', '\x2', '\x2', '#', '$', '\a', '-', '\x2', '\x2', 
		'$', '\b', '\x3', '\x2', '\x2', '\x2', '%', '&', '\a', ',', '\x2', '\x2', 
		'&', '\n', '\x3', '\x2', '\x2', '\x2', '\'', '(', '\a', '\x31', '\x2', 
		'\x2', '(', '\f', '\x3', '\x2', '\x2', '\x2', ')', '*', '\a', '*', '\x2', 
		'\x2', '*', '\xE', '\x3', '\x2', '\x2', '\x2', '+', ',', '\a', '+', '\x2', 
		'\x2', ',', '\x10', '\x3', '\x2', '\x2', '\x2', '-', '.', '\a', '.', '\x2', 
		'\x2', '.', '\x12', '\x3', '\x2', '\x2', '\x2', '/', '\x31', '\a', '\xF', 
		'\x2', '\x2', '\x30', '/', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\x32', '\x33', '\a', '\f', '\x2', '\x2', '\x33', '\x14', '\x3', '\x2', 
		'\x2', '\x2', '\x34', '\x36', '\t', '\x2', '\x2', '\x2', '\x35', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\x36', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\x35', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\x3', '\x2', 
		'\x2', '\x2', '\x38', '?', '\x3', '\x2', '\x2', '\x2', '\x39', ';', '\a', 
		'\x61', '\x2', '\x2', ':', '<', '\t', '\x3', '\x2', '\x2', ';', ':', '\x3', 
		'\x2', '\x2', '\x2', '<', '=', '\x3', '\x2', '\x2', '\x2', '=', ';', '\x3', 
		'\x2', '\x2', '\x2', '=', '>', '\x3', '\x2', '\x2', '\x2', '>', '@', '\x3', 
		'\x2', '\x2', '\x2', '?', '\x39', '\x3', '\x2', '\x2', '\x2', '?', '@', 
		'\x3', '\x2', '\x2', '\x2', '@', '\x16', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\x43', '\x4', '\x32', ';', '\x2', '\x42', '\x41', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\x44', '\x3', '\x2', '\x2', '\x2', '\x44', '\x42', '\x3', 
		'\x2', '\x2', '\x2', '\x44', '\x45', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x46', '\x3', '\x2', '\x2', '\x2', '\x46', 'J', '\a', '\x30', '\x2', 
		'\x2', 'G', 'I', '\x4', '\x32', ';', '\x2', 'H', 'G', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'L', '\x3', '\x2', '\x2', '\x2', 'J', 'H', '\x3', '\x2', '\x2', 
		'\x2', 'J', 'K', '\x3', '\x2', '\x2', '\x2', 'K', 'N', '\x3', '\x2', '\x2', 
		'\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 'M', 'O', '\x5', '\x1D', 
		'\xF', '\x2', 'N', 'M', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'Q', '\x3', '\x2', '\x2', '\x2', 'P', 'R', '\a', 'k', 
		'\x2', '\x2', 'Q', 'P', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\x3', '\x2', 
		'\x2', '\x2', 'R', '\x62', '\x3', '\x2', '\x2', '\x2', 'S', 'U', '\a', 
		'\x30', '\x2', '\x2', 'T', 'S', '\x3', '\x2', '\x2', '\x2', 'T', 'U', 
		'\x3', '\x2', '\x2', '\x2', 'U', 'W', '\x3', '\x2', '\x2', '\x2', 'V', 
		'X', '\x4', '\x32', ';', '\x2', 'W', 'V', '\x3', '\x2', '\x2', '\x2', 
		'X', 'Y', '\x3', '\x2', '\x2', '\x2', 'Y', 'W', '\x3', '\x2', '\x2', '\x2', 
		'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 'Z', '\\', '\x3', '\x2', '\x2', 
		'\x2', '[', ']', '\x5', '\x1D', '\xF', '\x2', '\\', '[', '\x3', '\x2', 
		'\x2', '\x2', '\\', ']', '\x3', '\x2', '\x2', '\x2', ']', '_', '\x3', 
		'\x2', '\x2', '\x2', '^', '`', '\a', 'k', '\x2', '\x2', '_', '^', '\x3', 
		'\x2', '\x2', '\x2', '_', '`', '\x3', '\x2', '\x2', '\x2', '`', '\x62', 
		'\x3', '\x2', '\x2', '\x2', '\x61', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\x61', 'T', '\x3', '\x2', '\x2', '\x2', '\x62', '\x18', '\x3', '\x2', 
		'\x2', '\x2', '\x63', '\x64', '\a', '\x31', '\x2', '\x2', '\x64', '\x65', 
		'\a', '\x31', '\x2', '\x2', '\x65', 'i', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'h', '\n', '\x4', '\x2', '\x2', 'g', '\x66', '\x3', '\x2', '\x2', '\x2', 
		'h', 'k', '\x3', '\x2', '\x2', '\x2', 'i', 'g', '\x3', '\x2', '\x2', '\x2', 
		'i', 'j', '\x3', '\x2', '\x2', '\x2', 'j', 'm', '\x3', '\x2', '\x2', '\x2', 
		'k', 'i', '\x3', '\x2', '\x2', '\x2', 'l', 'n', '\a', '\xF', '\x2', '\x2', 
		'm', 'l', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', '|', '\a', '\f', '\x2', '\x2', 
		'p', 'q', '\a', '\x31', '\x2', '\x2', 'q', 'r', '\a', ',', '\x2', '\x2', 
		'r', 'v', '\x3', '\x2', '\x2', '\x2', 's', 'u', '\v', '\x2', '\x2', '\x2', 
		't', 's', '\x3', '\x2', '\x2', '\x2', 'u', 'x', '\x3', '\x2', '\x2', '\x2', 
		'v', 'w', '\x3', '\x2', '\x2', '\x2', 'v', 't', '\x3', '\x2', '\x2', '\x2', 
		'w', 'y', '\x3', '\x2', '\x2', '\x2', 'x', 'v', '\x3', '\x2', '\x2', '\x2', 
		'y', 'z', '\a', ',', '\x2', '\x2', 'z', '|', '\a', '\x31', '\x2', '\x2', 
		'{', '\x63', '\x3', '\x2', '\x2', '\x2', '{', 'p', '\x3', '\x2', '\x2', 
		'\x2', '|', '}', '\x3', '\x2', '\x2', '\x2', '}', '~', '\b', '\r', '\x2', 
		'\x2', '~', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x81', '\t', 
		'\x5', '\x2', '\x2', '\x80', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x85', '\b', '\xE', '\x2', '\x2', '\x85', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x86', '\x88', '\t', '\x6', '\x2', 
		'\x2', '\x87', '\x89', '\t', '\a', '\x2', '\x2', '\x88', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x89', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8C', '\x4', '\x32', ';', 
		'\x2', '\x8B', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\x17', '\x2', '\x30', '\x37', '=', '?', '\x44', 'J', 'N', 'Q', 
		'T', 'Y', '\\', '_', '\x61', 'i', 'm', 'v', '{', '\x82', '\x88', '\x8D', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
