name: 'F# Test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  Test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.x'
        dotnet-quality: 'preview'

    - name: Build Tests # We need it to be able to retry
      run: |
        dotnet add "Sources/Tests/FSharpWrapperUnitTests" package Microsoft.NET.Test.Sdk # Update is required for GitHubActionsTestLogger to print anything
        dotnet add "Sources/Tests/FSharpWrapperUnitTests" package GitHubActionsTestLogger
        dotnet build Sources/Tests/FSharpWrapperUnitTests

    - name: Test
      if: ${{ matrix.os != 'ubuntu-latest' }}
      run: |
        dotnet test "Sources/Tests/FSharpWrapperUnitTests" -c Release -l GitHubActions

    - name: Test with coverage
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        dotnet test "Sources/Tests/FSharpWrapperUnitTests" -c Release -l GitHubActions --collect:"XPlat Code Coverage" --results-directory ./coverage -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

    - name: 'Send to codecov'
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v5
      with:
        directory: ./coverage
        flags: fsharp
