name: 'Interactive Test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  Test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.x'
        dotnet-quality: 'preview'

    - name: Build Tests # We need it to be able to retry
      run: |
        dotnet build Sources/Tests/InteractiveWrapperUnitTests -c Release
        dotnet build Sources/Tests/TerminalUnitTests -c Release
        
    - name: Test Interactive Wrapper
      if: ${{ matrix.os != 'ubuntu-latest' }}
      run: |
        dotnet test "Sources/Tests/InteractiveWrapperUnitTests" -c Release

    - name: Test Terminal Lib
      if: ${{ matrix.os != 'ubuntu-latest' }}
      run: |
        dotnet test "Sources/Tests/TerminalUnitTests" -c Release

    - name: Test with coverage
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        dotnet test "Sources/Tests/InteractiveWrapperUnitTests" -c Release --collect:"XPlat Code Coverage" --results-directory ./coverage -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        dotnet test "Sources/Tests/TerminalUnitTests" -c Release --collect:"XPlat Code Coverage" --results-directory ./coverage -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

    - name: 'Send to codecov'
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v5
      with:
        directory: ./coverage
        flags: interactive
