name: 'Terminal nightly builds'

on:
  push:
    branches:
      - '*'
    paths:
      - 'VERSION/**'

jobs:
  TerminalBuild:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
      
    - name: 'Build terminal for three OS'
      run: |
        cd Sources/Terminal/AngouriMath.Terminal
        ./publish-osx-x64.sh
        ./publish-win-x64.sh
        ./publish-linux-x64.sh
        ./pack-deb-linux-x64.sh

    - name: 'Pack'
      run: |
        zip -r terminal-win-x64.zip ./Sources/Terminal/AngouriMath.Terminal/publish-output/win-x64
        zip -r terminal-linux-x64.zip ./Sources/Terminal/AngouriMath.Terminal/publish-output/linux-x64
        zip -r terminal-osx-x64.zip ./Sources/Terminal/AngouriMath.Terminal/publish-output/osx-64
        
    - name: 'Release'
      run: |
        name=$(cat ./Sources/Terminal/VERSION/VERSION)
        echo "Version: $name"
     
        cp ./Sources/Terminal/AngouriMath.Terminal/publish-output/angourimath*.deb .
        deb=$(ls | grep angourimath*.deb)

        echo ${{ secrets.LAB_ACCESS_TOKEN }} > token.txt
        gh auth login --with-token < token.txt
        gh release create v$name 'terminal-win-x64.zip' 'terminal-linux-x64.zip' 'terminal-osx-x64.zip' $deb -p -R asc-community/AngouriMathLab -t 'AngouriMath.Terminal'
    
