name: 'Terminal nightly builds'

on:
  push:
    branches:
      - master
    paths:
      - 'Sources/Terminal/VERSION/**'

jobs:
  TerminalBuild:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
      
    - name: 'Build terminal for three OS'
      run: |
        cd Sources/Terminal/AngouriMath.Terminal
        ./publish-osx-x64.sh
        ./publish-win-x64.sh
        ./publish-linux-x64.sh
        ./pack-deb-linux-x64.sh

    - name: 'Pack'
      run: |
        zip -r angourimath-terminal-win-amd64.zip ./Sources/Terminal/AngouriMath.Terminal/publish-output/win-amd64
        zip -r angourimath-terminal-linux-amd64.zip ./Sources/Terminal/AngouriMath.Terminal/publish-output/linux-amd64
        zip -r angourimath-terminal-osx-amd64.zip ./Sources/Terminal/AngouriMath.Terminal/publish-output/osx-amd64
        
    - name: 'Release'
      run: |
        name=$(cat ./Sources/Terminal/VERSION/VERSION)
        echo "Version: $name"
     
        cp ./Sources/Terminal/AngouriMath.Terminal/publish-output/angourimath-terminal-amd64.deb .

        echo ${{ secrets.LAB_ACCESS_TOKEN }} > token.txt
        gh auth login --with-token < token.txt
        gh release create v$name 'angourimath-terminal-win-amd64.zip' 'angourimath-terminal-linux-amd64.zip' 'angourimath-terminal-osx-amd64.zip' 'angourimath-terminal-amd64.deb' -p -R asc-community/AngouriMathLab -t 'AngouriMath.Terminal' -n "Expand 'assets' and choose the one for your OS"
    
