name: Test

on: [push, pull_request]
jobs:
  Unit_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'
    - name: Setup JDK # Needed to run ANTLR
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    - name: Test
      run: |
        dotnet add "Tests/UnitTests" package Microsoft.NET.Test.Sdk # Update is required for GitHubActionsTestLogger to print anything
        dotnet add "Tests/UnitTests" package GitHubActionsTestLogger
        dotnet test "Tests/UnitTests" -c Release -l GitHubActions
